using FluentValidation;

namespace EventForge.Server.Validators.AI;

/// <summary>
/// FluentValidation validator for SimulateInboundDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SimulateInboundDtoValidator : AbstractValidator<Prym.DTOs.AI.SimulateInboundDto>
{
    public SimulateInboundDtoValidator()
    {
        RuleFor(x => x.PhoneNumber)
            .NotEmpty()
            .WithMessage("Il campo PhoneNumber è obbligatorio.")
            .MaximumLength(30)
            .WithMessage("Il campo PhoneNumber non può superare 30 caratteri.");

        RuleFor(x => x.MessageText)
            .NotEmpty()
            .WithMessage("Il campo MessageText è obbligatorio.")
            .MaximumLength(4096)
            .WithMessage("Il campo MessageText non può superare 4096 caratteri.");
    }
}
