using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for AdjustStockDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AdjustStockDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.AdjustStockDto>
{
    public AdjustStockDtoValidator()
    {
        RuleFor(x => x.NewQuantity)
            .InclusiveBetween((decimal)0, (decimal)999999999)
            .WithMessage("Il campo NewQuantity deve essere compreso tra 0 e 999999999.");

        RuleFor(x => x.PreviousQuantity)
            .InclusiveBetween((decimal)0, (decimal)999999999)
            .WithMessage("Il campo PreviousQuantity deve essere compreso tra 0 e 999999999.");

        RuleFor(x => x.Reason)
            .IsInEnum()
            .WithMessage("Il campo Reason deve essere un valore valido.");
    }
}
