using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateInventoryEntryDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateInventoryEntryDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateInventoryEntryDto>
{
    public CreateInventoryEntryDtoValidator()
    {
        RuleFor(x => x.Quantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Quantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
