using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateStorageLocationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateStorageLocationDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateStorageLocationDto>
{
    public CreateStorageLocationDtoValidator()
    {
        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(30)
            .WithMessage("Il campo Code non può superare 30 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(100)
            .WithMessage("Il campo Description non può superare 100 caratteri.");

        RuleFor(x => x.Capacity)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo Capacity deve essere compreso tra 0 e int.MaxValue.");

        RuleFor(x => x.Occupancy)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo Occupancy deve essere compreso tra 0 e int.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");

        RuleFor(x => x.Zone)
            .MaximumLength(20)
            .WithMessage("Il campo Zone non può superare 20 caratteri.");

        RuleFor(x => x.Floor)
            .MaximumLength(10)
            .WithMessage("Il campo Floor non può superare 10 caratteri.");

        RuleFor(x => x.Row)
            .MaximumLength(10)
            .WithMessage("Il campo Row non può superare 10 caratteri.");

        RuleFor(x => x.Column)
            .MaximumLength(10)
            .WithMessage("Il campo Column non può superare 10 caratteri.");

        RuleFor(x => x.Level)
            .MaximumLength(10)
            .WithMessage("Il campo Level non può superare 10 caratteri.");
    }
}
