using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateSerialDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateSerialDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateSerialDto>
{
    public CreateSerialDtoValidator()
    {
        RuleFor(x => x.SerialNumber)
            .NotEmpty()
            .WithMessage("Il campo SerialNumber è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo SerialNumber non può superare 100 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.Barcode)
            .MaximumLength(50)
            .WithMessage("Il campo Barcode non può superare 50 caratteri.");

        RuleFor(x => x.RfidTag)
            .MaximumLength(50)
            .WithMessage("Il campo RfidTag non può superare 50 caratteri.");
    }
}
