using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateInventoryDocumentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateInventoryDocumentDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateInventoryDocumentDto>
{
    public CreateInventoryDocumentDtoValidator()
    {
        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.Series)
            .MaximumLength(10)
            .WithMessage("Il campo Series non può superare 10 caratteri.");

        RuleFor(x => x.Number)
            .MaximumLength(30)
            .WithMessage("Il campo Number non può superare 30 caratteri.");
    }
}
