using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateLotDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateLotDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateLotDto>
{
    public CreateLotDtoValidator()
    {
        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");

        RuleFor(x => x.OriginalQuantity)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo OriginalQuantity deve essere compreso tra 0.01 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.Barcode)
            .MaximumLength(50)
            .WithMessage("Il campo Barcode non può superare 50 caratteri.");

        RuleFor(x => x.CountryOfOrigin)
            .MaximumLength(50)
            .WithMessage("Il campo CountryOfOrigin non può superare 50 caratteri.");
    }
}
