using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateStorageFacilityDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateStorageFacilityDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateStorageFacilityDto>
{
    public CreateStorageFacilityDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(30)
            .WithMessage("Il campo Code non può superare 30 caratteri.");

        RuleFor(x => x.Address)
            .MaximumLength(200)
            .WithMessage("Il campo Address non può superare 200 caratteri.");

        RuleFor(x => x.Phone)
            .MaximumLength(30)
            .WithMessage("Il campo Phone non può superare 30 caratteri.");

        RuleFor(x => x.Email)
            .MaximumLength(100)
            .WithMessage("Il campo Email non può superare 100 caratteri.")
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.");

        RuleFor(x => x.Manager)
            .MaximumLength(100)
            .WithMessage("Il campo Manager non può superare 100 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.AreaSquareMeters)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo AreaSquareMeters deve essere compreso tra 0 e int.MaxValue.");

        RuleFor(x => x.Capacity)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo Capacity deve essere compreso tra 0 e int.MaxValue.");
    }
}
