using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for CreateStockDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateStockDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.CreateStockDto>
{
    public CreateStockDtoValidator()
    {
        RuleFor(x => x.Quantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Quantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.ReservedQuantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ReservedQuantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.MinimumLevel)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MinimumLevel deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.MaximumLevel)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MaximumLevel deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.ReorderPoint)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ReorderPoint deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.ReorderQuantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ReorderQuantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.UnitCost)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo UnitCost deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");
    }
}
