using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for InventorySeedRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class InventorySeedRequestDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.InventorySeedRequestDto>
{
    public InventorySeedRequestDtoValidator()
    {
        RuleFor(x => x.Mode)
            .NotEmpty()
            .WithMessage("Il campo Mode è obbligatorio.");
    }
}
