using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for StockReconciliationApplyRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class StockReconciliationApplyRequestDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.StockReconciliationApplyRequestDto>
{
    public StockReconciliationApplyRequestDtoValidator()
    {
        RuleFor(x => x.ItemsToApply)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo ItemsToApply deve contenere almeno 1 elemento/i.");

        RuleFor(x => x.Reason)
            .NotEmpty()
            .WithMessage("Il campo Reason è obbligatorio.")
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
