using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for StockReconciliationBatchRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class StockReconciliationBatchRequestDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.StockReconciliationBatchRequestDto>
{
    public StockReconciliationBatchRequestDtoValidator()
    {
        RuleFor(x => x.StockIds)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo StockIds deve contenere almeno 1 elemento/i.");
    }
}
