using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for StockReconciliationRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class StockReconciliationRequestDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.StockReconciliationRequestDto>
{
    public StockReconciliationRequestDtoValidator()
    {
        RuleFor(x => x.StartingQuantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo StartingQuantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.DiscrepancyThreshold)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscrepancyThreshold deve essere compreso tra 0 e 100.");
    }
}
