using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for UpdateLotDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateLotDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.UpdateLotDto>
{
    public UpdateLotDtoValidator()
    {
        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");

        RuleFor(x => x.AvailableQuantity)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo AvailableQuantity deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.Barcode)
            .MaximumLength(50)
            .WithMessage("Il campo Barcode non può superare 50 caratteri.");

        RuleFor(x => x.CountryOfOrigin)
            .MaximumLength(50)
            .WithMessage("Il campo CountryOfOrigin non può superare 50 caratteri.");
    }
}
