using FluentValidation;

namespace EventForge.Server.Validators.Warehouse;

/// <summary>
/// FluentValidation validator for UpdateInventoryDocumentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateInventoryDocumentDtoValidator : AbstractValidator<Prym.DTOs.Warehouse.UpdateInventoryDocumentDto>
{
    public UpdateInventoryDocumentDtoValidator()
    {
        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
