using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateProductDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateProductDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateProductDto>
{
    public CreateProductDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.ShortDescription)
            .MaximumLength(50)
            .WithMessage("Il campo ShortDescription non può superare 50 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(100)
            .WithMessage("Il campo Code non può superare 100 caratteri.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.DefaultPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo DefaultPrice deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.ReorderPoint)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ReorderPoint deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.SafetyStock)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo SafetyStock deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.TargetStockLevel)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo TargetStockLevel deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.AverageDailyDemand)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo AverageDailyDemand deve essere compreso tra 0 e decimal.MaxValue.");
    }
}
