using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateProductUnitDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateProductUnitDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateProductUnitDto>
{
    public CreateProductUnitDtoValidator()
    {
        RuleFor(x => x.ConversionFactor)
            .InclusiveBetween((decimal)0.001, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ConversionFactor deve essere compreso tra 0.001 e decimal.MaxValue.");

        RuleFor(x => x.UnitType)
            .NotEmpty()
            .WithMessage("Il campo UnitType è obbligatorio.")
            .MaximumLength(20)
            .WithMessage("Il campo UnitType non può superare 20 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(100)
            .WithMessage("Il campo Description non può superare 100 caratteri.");
    }
}
