using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateBrandDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateBrandDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateBrandDto>
{
    public CreateBrandDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(1000)
            .WithMessage("Il campo Description non può superare 1000 caratteri.");

        RuleFor(x => x.Website)
            .MaximumLength(500)
            .WithMessage("Il campo Website non può superare 500 caratteri.");

        RuleFor(x => x.Country)
            .MaximumLength(100)
            .WithMessage("Il campo Country non può superare 100 caratteri.");
    }
}
