using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateProductCodeDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateProductCodeDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateProductCodeDto>
{
    public CreateProductCodeDtoValidator()
    {
        RuleFor(x => x.CodeType)
            .NotEmpty()
            .WithMessage("Il campo CodeType è obbligatorio.")
            .MaximumLength(30)
            .WithMessage("Il campo CodeType non può superare 30 caratteri.");

        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Code non può superare 100 caratteri.");

        RuleFor(x => x.AlternativeDescription)
            .MaximumLength(200)
            .WithMessage("Il campo AlternativeDescription non può superare 200 caratteri.");
    }
}
