using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateProductWithCodesAndUnitsDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateProductWithCodesAndUnitsDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateProductWithCodesAndUnitsDto>
{
    public CreateProductWithCodesAndUnitsDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.ShortDescription)
            .MaximumLength(50)
            .WithMessage("Il campo ShortDescription non può superare 50 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.DefaultPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo DefaultPrice deve essere compreso tra 0 e decimal.MaxValue.");
    }
}
