using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for CreateProductSupplierDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateProductSupplierDtoValidator : AbstractValidator<Prym.DTOs.Products.CreateProductSupplierDto>
{
    public CreateProductSupplierDtoValidator()
    {
        RuleFor(x => x.SupplierProductCode)
            .MaximumLength(100)
            .WithMessage("Il campo SupplierProductCode non può superare 100 caratteri.");

        RuleFor(x => x.PurchaseDescription)
            .MaximumLength(500)
            .WithMessage("Il campo PurchaseDescription non può superare 500 caratteri.");

        RuleFor(x => x.Currency)
            .MaximumLength(10)
            .WithMessage("Il campo Currency non può superare 10 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(1000)
            .WithMessage("Il campo Notes non può superare 1000 caratteri.");
    }
}
