using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for UpdateModelDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateModelDtoValidator : AbstractValidator<Prym.DTOs.Products.UpdateModelDto>
{
    public UpdateModelDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(1000)
            .WithMessage("Il campo Description non può superare 1000 caratteri.");

        RuleFor(x => x.ManufacturerPartNumber)
            .MaximumLength(100)
            .WithMessage("Il campo ManufacturerPartNumber non può superare 100 caratteri.");
    }
}
