using FluentValidation;

namespace EventForge.Server.Validators.Products;

/// <summary>
/// FluentValidation validator for UpdateProductBundleItemDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateProductBundleItemDtoValidator : AbstractValidator<Prym.DTOs.Products.UpdateProductBundleItemDto>
{
    public UpdateProductBundleItemDtoValidator()
    {
        RuleFor(x => x.Quantity)
            .InclusiveBetween((int)1, (int)10000)
            .WithMessage("Il campo Quantity deve essere compreso tra 1 e 10000.");
    }
}
