using FluentValidation;

namespace EventForge.Server.Validators.Notifications;

/// <summary>
/// FluentValidation validator for BulkNotificationActionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BulkNotificationActionDtoValidator : AbstractValidator<Prym.DTOs.Notifications.BulkNotificationActionDto>
{
    public BulkNotificationActionDtoValidator()
    {
        RuleFor(x => x.Action)
            .IsInEnum()
            .WithMessage("Il campo Action deve essere un valore valido.");
    }
}
