using FluentValidation;

namespace EventForge.Server.Validators.Notifications;

/// <summary>
/// FluentValidation validator for CreateNotificationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateNotificationDtoValidator : AbstractValidator<Prym.DTOs.Notifications.CreateNotificationDto>
{
    public CreateNotificationDtoValidator()
    {
        RuleFor(x => x.Type)
            .IsInEnum()
            .WithMessage("Il campo Type deve essere un valore valido.");

        RuleFor(x => x.Payload)
            .NotNull()
            .WithMessage("Il campo Payload è obbligatorio.")
            .SetValidator(new NotificationPayloadDtoValidator());
    }
}
