using FluentValidation;

namespace EventForge.Server.Validators.Notifications;

/// <summary>
/// FluentValidation validator for NotificationPreferencesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class NotificationPreferencesDtoValidator : AbstractValidator<Prym.DTOs.Notifications.NotificationPreferencesDto>
{
    public NotificationPreferencesDtoValidator()
    {
        RuleFor(x => x.PreferredLocale)
            .MaximumLength(10)
            .WithMessage("Il campo PreferredLocale non può superare 10 caratteri.");
    }
}
