using FluentValidation;

namespace EventForge.Server.Validators.Notifications;

/// <summary>
/// FluentValidation validator for NotificationExportRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class NotificationExportRequestDtoValidator : AbstractValidator<Prym.DTOs.Notifications.NotificationExportRequestDto>
{
    public NotificationExportRequestDtoValidator()
    {
        RuleFor(x => x.Format)
            .NotEmpty()
            .WithMessage("Il campo Format è obbligatorio.");

        RuleFor(x => x.MaxRecords)
            .InclusiveBetween((int)1, (int)100000)
            .WithMessage("Il campo MaxRecords deve essere compreso tra 1 e 100000.");
    }
}
