using FluentValidation;

namespace EventForge.Server.Validators.Notifications;

/// <summary>
/// FluentValidation validator for NotificationPayloadDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class NotificationPayloadDtoValidator : AbstractValidator<Prym.DTOs.Notifications.NotificationPayloadDto>
{
    public NotificationPayloadDtoValidator()
    {
        RuleFor(x => x.Title)
            .NotEmpty()
            .WithMessage("Il campo Title è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Message)
            .NotEmpty()
            .WithMessage("Il campo Message è obbligatorio.")
            .MaximumLength(1000)
            .WithMessage("Il campo Message non può superare 1000 caratteri.");

        RuleFor(x => x.ActionUrl)
            .MaximumLength(500)
            .WithMessage("Il campo ActionUrl non può superare 500 caratteri.");

        RuleFor(x => x.IconUrl)
            .MaximumLength(500)
            .WithMessage("Il campo IconUrl non può superare 500 caratteri.");

        RuleFor(x => x.Locale)
            .MaximumLength(10)
            .WithMessage("Il campo Locale non può superare 10 caratteri.");

        RuleFor(x => x.GroupId)
            .MaximumLength(100)
            .WithMessage("Il campo GroupId non può superare 100 caratteri.");
    }
}
