using FluentValidation;

namespace EventForge.Server.Validators.Promotions;

/// <summary>
/// FluentValidation validator for CreatePromotionRuleDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreatePromotionRuleDtoValidator : AbstractValidator<Prym.DTOs.Promotions.CreatePromotionRuleDto>
{
    public CreatePromotionRuleDtoValidator()
    {
        RuleFor(x => x.RuleType)
            .NotEmpty()
            .WithMessage("Il campo RuleType è obbligatorio.");

        RuleFor(x => x.DiscountPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscountPercentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.DiscountAmount)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo DiscountAmount deve essere compreso tra 0 e decimal.MaxValue.");
    }
}
