using FluentValidation;

namespace EventForge.Server.Validators.Promotions;

/// <summary>
/// FluentValidation validator for CreatePromotionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreatePromotionDtoValidator : AbstractValidator<Prym.DTOs.Promotions.CreatePromotionDto>
{
    public CreatePromotionDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.CouponCode)
            .MaximumLength(50)
            .WithMessage("Il campo CouponCode non può superare 50 caratteri.");

        RuleFor(x => x.MaxTotalDiscountPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo MaxTotalDiscountPercentage deve essere compreso tra 0 e 100.");
    }
}
