using FluentValidation;

namespace EventForge.Server.Validators.Promotions;

/// <summary>
/// FluentValidation validator for DuplicatePromotionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class DuplicatePromotionDtoValidator : AbstractValidator<Prym.DTOs.Promotions.DuplicatePromotionDto>
{
    public DuplicatePromotionDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.CouponCode)
            .MaximumLength(50)
            .WithMessage("Il campo CouponCode non può superare 50 caratteri.");
    }
}
