using FluentValidation;

namespace EventForge.Server.Validators.Promotions;

/// <summary>
/// FluentValidation validator for ValidateCouponRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ValidateCouponRequestDtoValidator : AbstractValidator<Prym.DTOs.Promotions.ValidateCouponRequestDto>
{
    public ValidateCouponRequestDtoValidator()
    {
        RuleFor(x => x.CouponCode)
            .NotEmpty()
            .WithMessage("Il campo CouponCode è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo CouponCode non può superare 50 caratteri.");
    }
}
