using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for CreateTenantDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateTenantDtoValidator : AbstractValidator<Prym.DTOs.Tenants.CreateTenantDto>
{
    public CreateTenantDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.")
            .Matches(@"^[a-z0-9-]+$")
            .WithMessage("Il campo Code non è nel formato corretto.");

        RuleFor(x => x.DisplayName)
            .NotEmpty()
            .WithMessage("Il campo DisplayName è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo DisplayName non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Domain)
            .MaximumLength(100)
            .WithMessage("Il campo Domain non può superare 100 caratteri.");

        RuleFor(x => x.ContactEmail)
            .NotEmpty()
            .WithMessage("Il campo ContactEmail è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo ContactEmail deve contenere un indirizzo email valido.")
            .MaximumLength(256)
            .WithMessage("Il campo ContactEmail non può superare 256 caratteri.");

        RuleFor(x => x.MaxUsers)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxUsers deve essere compreso tra 1 e int.MaxValue.");
    }
}
