using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for CreateTenantUserDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateTenantUserDtoValidator : AbstractValidator<Prym.DTOs.Tenants.CreateTenantUserDto>
{
    public CreateTenantUserDtoValidator()
    {
        RuleFor(x => x.Username)
            .NotEmpty()
            .WithMessage("Il campo Username è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Username non può superare 100 caratteri.");

        RuleFor(x => x.Email)
            .NotEmpty()
            .WithMessage("Il campo Email è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.")
            .MaximumLength(256)
            .WithMessage("Il campo Email non può superare 256 caratteri.");

        RuleFor(x => x.FirstName)
            .NotEmpty()
            .WithMessage("Il campo FirstName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo FirstName non può superare 100 caratteri.");

        RuleFor(x => x.LastName)
            .NotEmpty()
            .WithMessage("Il campo LastName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo LastName non può superare 100 caratteri.");
    }
}
