using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for SwitchTenantRequest.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SwitchTenantRequestValidator : AbstractValidator<Prym.DTOs.Tenants.SwitchTenantRequest>
{
    public SwitchTenantRequestValidator()
    {
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
