using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for TenantSearchDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class TenantSearchDtoValidator : AbstractValidator<Prym.DTOs.Tenants.TenantSearchDto>
{
    public TenantSearchDtoValidator()
    {
        RuleFor(x => x.SearchTerm)
            .MaximumLength(100)
            .WithMessage("Il campo SearchTerm non può superare 100 caratteri.");

        RuleFor(x => x.Domain)
            .MaximumLength(100)
            .WithMessage("Il campo Domain non può superare 100 caratteri.");
    }
}
