using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for UpdateTenantDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateTenantDtoValidator : AbstractValidator<Prym.DTOs.Tenants.UpdateTenantDto>
{
    public UpdateTenantDtoValidator()
    {
        RuleFor(x => x.DisplayName)
            .NotEmpty()
            .WithMessage("Il campo DisplayName è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo DisplayName non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Domain)
            .MaximumLength(100)
            .WithMessage("Il campo Domain non può superare 100 caratteri.");

        RuleFor(x => x.ContactEmail)
            .NotEmpty()
            .WithMessage("Il campo ContactEmail è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo ContactEmail deve contenere un indirizzo email valido.")
            .MaximumLength(256)
            .WithMessage("Il campo ContactEmail non può superare 256 caratteri.");

        RuleFor(x => x.MaxUsers)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxUsers deve essere compreso tra 1 e int.MaxValue.");
    }
}
