using FluentValidation;

namespace EventForge.Server.Validators.Tenants;

/// <summary>
/// FluentValidation validator for UpdateTenantLimitsDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateTenantLimitsDtoValidator : AbstractValidator<Prym.DTOs.Tenants.UpdateTenantLimitsDto>
{
    public UpdateTenantLimitsDtoValidator()
    {
        RuleFor(x => x.MaxUsers)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxUsers deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxStorage)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxStorage deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxStorageBytes)
            .InclusiveBetween((long)1, (long)long.MaxValue)
            .WithMessage("Il campo MaxStorageBytes deve essere compreso tra 1 e long.MaxValue.");

        RuleFor(x => x.MaxApiCalls)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxApiCalls deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxEventsPerMonth)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxEventsPerMonth deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxDocuments)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxDocuments deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxProducts)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MaxProducts deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
