using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for BackupRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BackupRequestDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.BackupRequestDto>
{
    public BackupRequestDtoValidator()
    {
        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");
    }
}
