using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for CreateUserDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateUserDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.CreateUserDto>
{
    public CreateUserDtoValidator()
    {
        RuleFor(x => x.Username)
            .NotEmpty()
            .WithMessage("Il campo Username è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Username non può superare 100 caratteri.");

        RuleFor(x => x.Email)
            .NotEmpty()
            .WithMessage("Il campo Email è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.");

        RuleFor(x => x.FirstName)
            .NotEmpty()
            .WithMessage("Il campo FirstName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo FirstName non può superare 100 caratteri.");

        RuleFor(x => x.LastName)
            .NotEmpty()
            .WithMessage("Il campo LastName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo LastName non può superare 100 caratteri.");

        RuleFor(x => x.Phone)
            .MaximumLength(100)
            .WithMessage("Il campo Phone non può superare 100 caratteri.");
    }
}
