using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for CreateConfigurationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateConfigurationDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.CreateConfigurationDto>
{
    public CreateConfigurationDtoValidator()
    {
        RuleFor(x => x.Key)
            .NotEmpty()
            .WithMessage("Il campo Key è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Key non può superare 100 caratteri.");

        RuleFor(x => x.Value)
            .NotEmpty()
            .WithMessage("Il campo Value è obbligatorio.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");
    }
}
