using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for EndImpersonationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class EndImpersonationDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.EndImpersonationDto>
{
    public EndImpersonationDtoValidator()
    {
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
