using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for ExportRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ExportRequestDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.ExportRequestDto>
{
    public ExportRequestDtoValidator()
    {
        RuleFor(x => x.Type)
            .NotEmpty()
            .WithMessage("Il campo Type è obbligatorio.");

        RuleFor(x => x.Format)
            .NotEmpty()
            .WithMessage("Il campo Format è obbligatorio.");

        RuleFor(x => x.FileName)
            .MaximumLength(200)
            .WithMessage("Il campo FileName non può superare 200 caratteri.");
    }
}
