using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for ForcePasswordChangeDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ForcePasswordChangeDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.ForcePasswordChangeDto>
{
    public ForcePasswordChangeDtoValidator()
    {
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
