using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for QuickUserActionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class QuickUserActionDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.QuickUserActionDto>
{
    public QuickUserActionDtoValidator()
    {
        RuleFor(x => x.Action)
            .NotEmpty()
            .WithMessage("Il campo Action è obbligatorio.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
