using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for SecurityValidationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SecurityValidationDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.SecurityValidationDto>
{
    public SecurityValidationDtoValidator()
    {
        RuleFor(x => x.ValidationCode)
            .NotEmpty()
            .WithMessage("Il campo ValidationCode è obbligatorio.");

        RuleFor(x => x.RequestType)
            .NotEmpty()
            .WithMessage("Il campo RequestType è obbligatorio.");

        RuleFor(x => x.Action)
            .NotEmpty()
            .WithMessage("Il campo Action è obbligatorio.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
