using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for SmtpTestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SmtpTestDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.SmtpTestDto>
{
    public SmtpTestDtoValidator()
    {
        RuleFor(x => x.ToEmail)
            .NotEmpty()
            .WithMessage("Il campo ToEmail è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo ToEmail deve contenere un indirizzo email valido.");

        RuleFor(x => x.Subject)
            .NotEmpty()
            .WithMessage("Il campo Subject è obbligatorio.");

        RuleFor(x => x.Body)
            .NotEmpty()
            .WithMessage("Il campo Body è obbligatorio.");
    }
}
