using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for UpdateConfigurationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateConfigurationDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.UpdateConfigurationDto>
{
    public UpdateConfigurationDtoValidator()
    {
        RuleFor(x => x.Value)
            .NotEmpty()
            .WithMessage("Il campo Value è obbligatorio.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");
    }
}
