using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for UpdateUserStatusDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateUserStatusDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.UpdateUserStatusDto>
{
    public UpdateUserStatusDtoValidator()
    {
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
