using FluentValidation;

namespace EventForge.Server.Validators.SuperAdmin;

/// <summary>
/// FluentValidation validator for UserSearchDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UserSearchDtoValidator : AbstractValidator<Prym.DTOs.SuperAdmin.UserSearchDto>
{
    public UserSearchDtoValidator()
    {
        RuleFor(x => x.SearchTerm)
            .MaximumLength(100)
            .WithMessage("Il campo SearchTerm non può superare 100 caratteri.");
    }
}
