using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for CalculateChangeRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CalculateChangeRequestDtoValidator : AbstractValidator<Prym.DTOs.Store.CalculateChangeRequestDto>
{
    public CalculateChangeRequestDtoValidator()
    {
        RuleFor(x => x.TotalAmount)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo TotalAmount deve essere compreso tra 0.01 e decimal.MaxValue.");

        RuleFor(x => x.ReceivedAmount)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ReceivedAmount deve essere compreso tra 0.01 e decimal.MaxValue.");
    }
}
