using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for CloseFiscalDrawerSessionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CloseFiscalDrawerSessionDtoValidator : AbstractValidator<Prym.DTOs.Store.CloseFiscalDrawerSessionDto>
{
    public CloseFiscalDrawerSessionDtoValidator()
    {
        RuleFor(x => x.ClosingBalance)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo ClosingBalance deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
