using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for CreateFiscalDrawerTransactionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateFiscalDrawerTransactionDtoValidator : AbstractValidator<Prym.DTOs.Store.CreateFiscalDrawerTransactionDto>
{
    public CreateFiscalDrawerTransactionDtoValidator()
    {
        RuleFor(x => x.TransactionType)
            .IsInEnum()
            .WithMessage("Il campo TransactionType deve essere un valore valido.");

        RuleFor(x => x.PaymentType)
            .IsInEnum()
            .WithMessage("Il campo PaymentType deve essere un valore valido.");

        RuleFor(x => x.Amount)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Amount deve essere compreso tra 0.01 e decimal.MaxValue.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");
    }
}
