using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for OpenFiscalDrawerSessionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class OpenFiscalDrawerSessionDtoValidator : AbstractValidator<Prym.DTOs.Store.OpenFiscalDrawerSessionDto>
{
    public OpenFiscalDrawerSessionDtoValidator()
    {
        RuleFor(x => x.OpeningBalance)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo OpeningBalance deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
