using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for StoreUserPinDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class StoreUserPinDtoValidator : AbstractValidator<Prym.DTOs.Store.StoreUserPinDto>
{
    public StoreUserPinDtoValidator()
    {
        RuleFor(x => x.Pin)
            .NotEmpty()
            .WithMessage("Il campo Pin è obbligatorio.")
            .Matches(Prym.DTOs.Store.StoreUserPinDto.PinPattern)
            .WithMessage("Il campo Pin non è nel formato corretto.");
    }
}
