using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for UpdateFiscalDrawerDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateFiscalDrawerDtoValidator : AbstractValidator<Prym.DTOs.Store.UpdateFiscalDrawerDto>
{
    public UpdateFiscalDrawerDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(20)
            .WithMessage("Il campo Code non può superare 20 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");

        RuleFor(x => x.CurrencyCode)
            .NotEmpty()
            .WithMessage("Il campo CurrencyCode è obbligatorio.")
            .MaximumLength(3)
            .WithMessage("Il campo CurrencyCode non può superare 3 caratteri.")
            .Matches(@"^[A-Z]{3}$")
            .WithMessage("Il campo CurrencyCode non è nel formato corretto.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");
    }
}
