using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for UpdateCashierShiftDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateCashierShiftDtoValidator : AbstractValidator<Prym.DTOs.Store.UpdateCashierShiftDto>
{
    public UpdateCashierShiftDtoValidator()
    {
        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
