using FluentValidation;

namespace EventForge.Server.Validators.Store;

/// <summary>
/// FluentValidation validator for UpdateCashDenominationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateCashDenominationDtoValidator : AbstractValidator<Prym.DTOs.Store.UpdateCashDenominationDto>
{
    public UpdateCashDenominationDtoValidator()
    {
        RuleFor(x => x.Quantity)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo Quantity deve essere compreso tra 0 e int.MaxValue.");
    }
}
