using FluentValidation;

namespace EventForge.Server.Validators.DevTools;

/// <summary>
/// FluentValidation validator for GenerateProductsRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class GenerateProductsRequestDtoValidator : AbstractValidator<Prym.DTOs.DevTools.GenerateProductsRequestDto>
{
    public GenerateProductsRequestDtoValidator()
    {
        RuleFor(x => x.Count)
            .InclusiveBetween((int)1, (int)20000)
            .WithMessage("Il campo Count deve essere compreso tra 1 e 20000.");

        RuleFor(x => x.BatchSize)
            .InclusiveBetween((int)10, (int)1000)
            .WithMessage("Il campo BatchSize deve essere compreso tra 10 e 1000.");
    }
}
