using System.ComponentModel.DataAnnotations;

namespace Prym.Hub.Data.Entities;

/// <summary>
/// Represents a registered installation of Prym (server, client, or both).
/// </summary>
public class Installation
{
    public Guid Id { get; set; } = Guid.NewGuid();

    /// <summary>
    /// Human-readable unique code generated by the Agent on first startup.
    /// Format: EF-{hostname8}-{yyyyMMddHHmmss}-{16hexrandom}
    /// Used to identify the agent across re-enrollments.
    /// </summary>
    [MaxLength(100)]
    public string? InstallationCode { get; set; }

    [Required, MaxLength(200)]
    public string Name { get; set; } = string.Empty;

    [MaxLength(500)]
    public string? Location { get; set; }

    /// <summary>Server, Client, or Both</summary>
    public InstallationComponents Components { get; set; }

    [MaxLength(50)]
    public string? InstalledVersionServer { get; set; }

    [MaxLength(50)]
    public string? InstalledVersionClient { get; set; }

    public InstallationStatus Status { get; set; } = InstallationStatus.Unknown;

    public DateTime? LastSeen { get; set; }

    public DateTime RegisteredAt { get; set; } = DateTime.UtcNow;

    [MaxLength(500)]
    public string? Notes { get; set; }

    /// <summary>API key used by the agent to authenticate with the hub.</summary>
    [Required, MaxLength(200)]
    public string ApiKey { get; set; } = string.Empty;

    // ── Runtime identity (sent by Agent on every connect) ─────────────────
    /// <summary>Hostname of the machine running this agent.</summary>
    [MaxLength(200)]
    public string? MachineName { get; set; }

    /// <summary>Operating system version string (e.g. "Windows 11 Pro 22H2 Build 22621").</summary>
    [MaxLength(300)]
    public string? OSVersion { get; set; }

    /// <summary>.NET runtime version the agent is running on (e.g. "10.0.0").</summary>
    [MaxLength(50)]
    public string? DotNetVersion { get; set; }

    /// <summary>Prym UpdateAgent version (Nerdbank.GitVersioning).</summary>
    [MaxLength(50)]
    public string? AgentVersion { get; set; }

    /// <summary>Last known IP address of the agent (set by Hub from HTTP context).</summary>
    [MaxLength(100)]
    public string? IpAddress { get; set; }

    /// <summary>Comma-separated classification tags sent by the agent (e.g. "production,milan").</summary>
    [MaxLength(500)]
    public string? Tags { get; set; }

    // ── Revocation ────────────────────────────────────────────────────────
    /// <summary>When true, the API key is blocked and the agent cannot connect.</summary>
    public bool IsRevoked { get; set; }

    /// <summary>UTC timestamp when the key was revoked.</summary>
    public DateTime? RevokedAt { get; set; }

    /// <summary>Optional reason for revocation (admin note).</summary>
    [MaxLength(500)]
    public string? RevokedReason { get; set; }

    /// <summary>Controls whether updates are installed automatically or require manual operator approval.</summary>
    public InstallationUpdateMode UpdateMode { get; set; } = InstallationUpdateMode.Automatic;

    public ICollection<UpdateHistory> UpdateHistory { get; set; } = [];
}

public enum InstallationComponents { Server = 1, Client = 2, Both = 3 }

public enum InstallationStatus { Unknown, Online, Offline, Updating, Error }

public enum InstallationUpdateMode { Automatic = 0, Manual = 1 }
