using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for CreateFidelityPointsBaseRateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateFidelityPointsBaseRateDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.CreateFidelityPointsBaseRateDto>
{
    public CreateFidelityPointsBaseRateDtoValidator()
    {
        RuleFor(x => x.Rate)
            .InclusiveBetween((decimal)0.01, (decimal)1000)
            .WithMessage("Il campo Rate deve essere compreso tra 0.01 e 1000.");
    }
}
