using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for CreateFidelityPointsCampaignDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateFidelityPointsCampaignDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.CreateFidelityPointsCampaignDto>
{
    public CreateFidelityPointsCampaignDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Multiplier)
            .InclusiveBetween((decimal)0.01, (decimal)100)
            .WithMessage("Il campo Multiplier deve essere compreso tra 0.01 e 100.");
    }
}
