using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for CreateFidelityTierMultiplierDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateFidelityTierMultiplierDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.CreateFidelityTierMultiplierDto>
{
    public CreateFidelityTierMultiplierDtoValidator()
    {
        RuleFor(x => x.Multiplier)
            .InclusiveBetween((decimal)0.01, (decimal)100)
            .WithMessage("Il campo Multiplier deve essere compreso tra 0.01 e 100.");
    }
}
