using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for CreateFidelityCardDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateFidelityCardDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.CreateFidelityCardDto>
{
    public CreateFidelityCardDtoValidator()
    {
        RuleFor(x => x.CardNumber)
            .NotEmpty()
            .WithMessage("Il campo CardNumber è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo CardNumber non può superare 50 caratteri.");

        RuleFor(x => x.DiscountPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscountPercentage deve essere compreso tra 0 e 100.");
    }
}
