using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for ModifyFidelityPointsDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ModifyFidelityPointsDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.ModifyFidelityPointsDto>
{
    public ModifyFidelityPointsDtoValidator()
    {
        RuleFor(x => x.Points)
            .InclusiveBetween((int)1, (int)100000)
            .WithMessage("Il campo Points deve essere compreso tra 1 e 100000.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");
    }
}
