using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for UpdateFidelityCardDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateFidelityCardDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.UpdateFidelityCardDto>
{
    public UpdateFidelityCardDtoValidator()
    {
        RuleFor(x => x.DiscountPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscountPercentage deve essere compreso tra 0 e 100.");
    }
}
