using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for UpdateFidelityPointsBaseRateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateFidelityPointsBaseRateDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.UpdateFidelityPointsBaseRateDto>
{
    public UpdateFidelityPointsBaseRateDtoValidator()
    {
        RuleFor(x => x.Rate)
            .InclusiveBetween((decimal)0.01, (decimal)1000)
            .WithMessage("Il campo Rate deve essere compreso tra 0.01 e 1000.");
    }
}
