using FluentValidation;

namespace EventForge.Server.Validators.Business.Fidelity;

/// <summary>
/// FluentValidation validator for UpdateFidelityTierDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateFidelityTierDtoValidator : AbstractValidator<Prym.DTOs.Business.Fidelity.UpdateFidelityTierDto>
{
    public UpdateFidelityTierDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Color)
            .MaximumLength(50)
            .WithMessage("Il campo Color non può superare 50 caratteri.");

        RuleFor(x => x.Icon)
            .MaximumLength(100)
            .WithMessage("Il campo Icon non può superare 100 caratteri.");

        RuleFor(x => x.MinimumSpendThreshold)
            .InclusiveBetween((decimal)0, (decimal)999999999)
            .WithMessage("Il campo MinimumSpendThreshold deve essere compreso tra 0 e 999999999.");

        RuleFor(x => x.EvaluationPeriodMonths)
            .InclusiveBetween((int)1, (int)120)
            .WithMessage("Il campo EvaluationPeriodMonths deve essere compreso tra 1 e 120.");
    }
}
