using FluentValidation;

namespace EventForge.Server.Validators.Alerts;

/// <summary>
/// FluentValidation validator for UpdateAlertConfigRequest.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateAlertConfigRequestValidator : AbstractValidator<Prym.DTOs.Alerts.UpdateAlertConfigRequest>
{
    public UpdateAlertConfigRequestValidator()
    {
        RuleFor(x => x.PriceIncreaseThresholdPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo PriceIncreaseThresholdPercentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.PriceDecreaseThresholdPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo PriceDecreaseThresholdPercentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.VolatilityThresholdPercentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo VolatilityThresholdPercentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.DaysWithoutUpdateThreshold)
            .InclusiveBetween((int)1, (int)365)
            .WithMessage("Il campo DaysWithoutUpdateThreshold deve essere compreso tra 1 e 365.");

        RuleFor(x => x.NotificationFrequency)
            .NotEmpty()
            .WithMessage("Il campo NotificationFrequency è obbligatorio.");
    }
}
