using FluentValidation;

namespace EventForge.Server.Validators.Licensing;

/// <summary>
/// FluentValidation validator for UpdateFeatureTemplateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateFeatureTemplateDtoValidator : AbstractValidator<Prym.DTOs.Licensing.UpdateFeatureTemplateDto>
{
    public UpdateFeatureTemplateDtoValidator()
    {
        RuleFor(x => x.DisplayName)
            .NotEmpty()
            .WithMessage("Il campo DisplayName è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo DisplayName non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(1000)
            .WithMessage("Il campo Description non può superare 1000 caratteri.");

        RuleFor(x => x.Category)
            .NotEmpty()
            .WithMessage("Il campo Category è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Category non può superare 100 caratteri.");

        RuleFor(x => x.MinimumTierLevel)
            .InclusiveBetween((int)1, (int)10)
            .WithMessage("Il campo MinimumTierLevel deve essere compreso tra 1 e 10.");
    }
}
