using FluentValidation;

namespace EventForge.Server.Validators.Profile;

/// <summary>
/// FluentValidation validator for ChangePasswordDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ChangePasswordDtoValidator : AbstractValidator<Prym.DTOs.Profile.ChangePasswordDto>
{
    public ChangePasswordDtoValidator()
    {
        RuleFor(x => x.CurrentPassword)
            .NotEmpty()
            .WithMessage("Il campo CurrentPassword è obbligatorio.");

        RuleFor(x => x.NewPassword)
            .NotEmpty()
            .WithMessage("Il campo NewPassword è obbligatorio.")
            .MinimumLength(8)
            .WithMessage("Il campo NewPassword deve contenere almeno 8 caratteri.");

        RuleFor(x => x.ConfirmPassword)
            .NotEmpty()
            .WithMessage("Il campo ConfirmPassword è obbligatorio.")
            .Equal(x => x.NewPassword)
            .WithMessage("Il campo ConfirmPassword deve corrispondere a NewPassword.");
    }
}
