using FluentValidation;

namespace EventForge.Server.Validators.Profile;

/// <summary>
/// FluentValidation validator for UpdateProfileDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateProfileDtoValidator : AbstractValidator<Prym.DTOs.Profile.UpdateProfileDto>
{
    public UpdateProfileDtoValidator()
    {
        RuleFor(x => x.FirstName)
            .NotEmpty()
            .WithMessage("Il campo FirstName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo FirstName non può superare 100 caratteri.");

        RuleFor(x => x.LastName)
            .NotEmpty()
            .WithMessage("Il campo LastName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo LastName non può superare 100 caratteri.");

        RuleFor(x => x.Email)
            .NotEmpty()
            .WithMessage("Il campo Email è obbligatorio.")
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.")
            .MaximumLength(256)
            .WithMessage("Il campo Email non può superare 256 caratteri.");

        RuleFor(x => x.PhoneNumber)
            .MaximumLength(20)
            .WithMessage("Il campo PhoneNumber non può superare 20 caratteri.");

        RuleFor(x => x.PreferredLanguage)
            .MaximumLength(10)
            .WithMessage("Il campo PreferredLanguage non può superare 10 caratteri.");

        RuleFor(x => x.TimeZone)
            .MaximumLength(50)
            .WithMessage("Il campo TimeZone non può superare 50 caratteri.");
    }
}
