using FluentValidation;

namespace EventForge.Server.Validators.Profile;

/// <summary>
/// FluentValidation validator for UserDisplayPreferencesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UserDisplayPreferencesDtoValidator : AbstractValidator<Prym.DTOs.Profile.UserDisplayPreferencesDto>
{
    public UserDisplayPreferencesDtoValidator()
    {
        RuleFor(x => x.BodyFont)
            .MaximumLength(50)
            .WithMessage("Il campo BodyFont non può superare 50 caratteri.");

        RuleFor(x => x.HeadingsFont)
            .MaximumLength(50)
            .WithMessage("Il campo HeadingsFont non può superare 50 caratteri.");

        RuleFor(x => x.MonospaceFont)
            .MaximumLength(50)
            .WithMessage("Il campo MonospaceFont non può superare 50 caratteri.");

        RuleFor(x => x.ContentFont)
            .MaximumLength(50)
            .WithMessage("Il campo ContentFont non può superare 50 caratteri.");

        RuleFor(x => x.BaseFontSize)
            .InclusiveBetween((int)12, (int)24)
            .WithMessage("Il campo BaseFontSize deve essere compreso tra 12 e 24.");

        RuleFor(x => x.PrimaryFontFamily)
            .MaximumLength(50)
            .WithMessage("Il campo PrimaryFontFamily non può superare 50 caratteri.");

        RuleFor(x => x.MonospaceFontFamily)
            .MaximumLength(50)
            .WithMessage("Il campo MonospaceFontFamily non può superare 50 caratteri.");

        RuleFor(x => x.PreferredTheme)
            .MaximumLength(50)
            .WithMessage("Il campo PreferredTheme non può superare 50 caratteri.");
    }
}
