using FluentValidation;

namespace EventForge.Server.Validators.Events;

/// <summary>
/// FluentValidation validator for CreateEventDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateEventDtoValidator : AbstractValidator<Prym.DTOs.Events.CreateEventDto>
{
    public CreateEventDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.ShortDescription)
            .NotEmpty()
            .WithMessage("Il campo ShortDescription è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo ShortDescription non può superare 200 caratteri.");

        RuleFor(x => x.Location)
            .MaximumLength(200)
            .WithMessage("Il campo Location non può superare 200 caratteri.");

        RuleFor(x => x.Capacity)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo Capacity deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.Color)
            .MaximumLength(7)
            .WithMessage("Il campo Color non può superare 7 caratteri.");

        RuleFor(x => x.AssignedToUserId)
            .MaximumLength(100)
            .WithMessage("Il campo AssignedToUserId non può superare 100 caratteri.");
    }
}
