using FluentValidation;

namespace EventForge.Server.Validators.VatRates;

/// <summary>
/// FluentValidation validator for CreateVatNatureDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateVatNatureDtoValidator : AbstractValidator<Prym.DTOs.VatRates.CreateVatNatureDto>
{
    public CreateVatNatureDtoValidator()
    {
        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MaximumLength(10)
            .WithMessage("Il campo Code non può superare 10 caratteri.");

        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");
    }
}
