using FluentValidation;

namespace EventForge.Server.Validators.VatRates;

/// <summary>
/// FluentValidation validator for UpdateVatRateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateVatRateDtoValidator : AbstractValidator<Prym.DTOs.VatRates.UpdateVatRateDto>
{
    public UpdateVatRateDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Percentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo Percentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");

        RuleFor(x => x.FiscalCode)
            .InclusiveBetween((int)1, (int)10)
            .WithMessage("Il campo FiscalCode deve essere compreso tra 1 e 10.");
    }
}
