using FluentValidation;

namespace EventForge.Server.Validators.Reports;

/// <summary>
/// FluentValidation validator for CreateReportDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateReportDtoValidator : AbstractValidator<Prym.DTOs.Reports.CreateReportDto>
{
    public CreateReportDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(1000)
            .WithMessage("Il campo Description non può superare 1000 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(100)
            .WithMessage("Il campo Category non può superare 100 caratteri.");
    }
}
