namespace Prym.DTOs.Analytics;

/// <summary>
/// Sales totals aggregated for a single time period.
/// </summary>
public class SalesTrendDto
{
    /// <summary>Period label (yyyy-MM-dd).</summary>
    public string Date { get; set; } = string.Empty;

    /// <summary>Total net sales amount in this period.</summary>
    public decimal TotalAmount { get; set; }

    /// <summary>Number of documents in this period.</summary>
    public int DocumentCount { get; set; }

    /// <summary>Average order value in this period.</summary>
    public decimal AverageOrderValue { get; set; }
}

/// <summary>
/// A product ranked by revenue or quantity sold.
/// </summary>
public class TopProductDto
{
    /// <summary>Rank position (1 = best seller).</summary>
    public int Rank { get; set; }

    /// <summary>Product unique identifier.</summary>
    public Guid? ProductId { get; set; }

    /// <summary>Product name or description.</summary>
    public string ProductName { get; set; } = string.Empty;

    /// <summary>Total quantity sold.</summary>
    public decimal TotalQuantity { get; set; }

    /// <summary>Total revenue generated by this product.</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>Total discount applied to this product.</summary>
    public decimal TotalDiscount { get; set; }
}

/// <summary>
/// Aggregate dashboard data for sales analytics.
/// </summary>
public class SalesAnalyticsDashboardDto
{
    /// <summary>Sales trend over the requested period.</summary>
    public List<SalesTrendDto> SalesTrend { get; set; } = new();

    /// <summary>Top products ordered by revenue.</summary>
    public List<TopProductDto> TopProducts { get; set; } = new();

    /// <summary>Total revenue in the period.</summary>
    public decimal TotalRevenue { get; set; }

    /// <summary>Total number of documents in the period.</summary>
    public int TotalDocuments { get; set; }

    /// <summary>Average order value across the period.</summary>
    public decimal AverageOrderValue { get; set; }

    /// <summary>Start of the queried date range.</summary>
    public DateTime? DateFrom { get; set; }

    /// <summary>End of the queried date range.</summary>
    public DateTime? DateTo { get; set; }
}
