using FluentValidation;

namespace EventForge.Server.Validators.Calendar;

/// <summary>
/// FluentValidation validator for UpdateCalendarReminderDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateCalendarReminderDtoValidator : AbstractValidator<Prym.DTOs.Calendar.UpdateCalendarReminderDto>
{
    public UpdateCalendarReminderDtoValidator()
    {
        RuleFor(x => x.Title)
            .NotEmpty()
            .WithMessage("Il campo Title è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(1000)
            .WithMessage("Il campo Description non può superare 1000 caratteri.");

        RuleFor(x => x.RecurrenceInterval)
            .InclusiveBetween((int)1, (int)365)
            .WithMessage("Il campo RecurrenceInterval deve essere compreso tra 1 e 365.");

        RuleFor(x => x.CompletionNotes)
            .MaximumLength(500)
            .WithMessage("Il campo CompletionNotes non può superare 500 caratteri.");

        RuleFor(x => x.Color)
            .MaximumLength(7)
            .WithMessage("Il campo Color non può superare 7 caratteri.");

        RuleFor(x => x.AssignedToUserId)
            .MaximumLength(100)
            .WithMessage("Il campo AssignedToUserId non può superare 100 caratteri.");
    }
}
