using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for CreateMembershipCardDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateMembershipCardDtoValidator : AbstractValidator<Prym.DTOs.Teams.CreateMembershipCardDto>
{
    public CreateMembershipCardDtoValidator()
    {
        RuleFor(x => x.CardNumber)
            .NotEmpty()
            .WithMessage("Il campo CardNumber è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo CardNumber non può superare 50 caratteri.");

        RuleFor(x => x.Federation)
            .NotEmpty()
            .WithMessage("Il campo Federation è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Federation non può superare 100 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(50)
            .WithMessage("Il campo Category non può superare 50 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
