using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for CreateDocumentReferenceDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentReferenceDtoValidator : AbstractValidator<Prym.DTOs.Teams.CreateDocumentReferenceDto>
{
    public CreateDocumentReferenceDtoValidator()
    {
        RuleFor(x => x.OwnerType)
            .MaximumLength(50)
            .WithMessage("Il campo OwnerType non può superare 50 caratteri.");

        RuleFor(x => x.FileName)
            .NotEmpty()
            .WithMessage("Il campo FileName è obbligatorio.")
            .MaximumLength(255)
            .WithMessage("Il campo FileName non può superare 255 caratteri.");

        RuleFor(x => x.MimeType)
            .NotEmpty()
            .WithMessage("Il campo MimeType è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo MimeType non può superare 100 caratteri.");

        RuleFor(x => x.StorageKey)
            .NotEmpty()
            .WithMessage("Il campo StorageKey è obbligatorio.")
            .MaximumLength(500)
            .WithMessage("Il campo StorageKey non può superare 500 caratteri.");

        RuleFor(x => x.Url)
            .MaximumLength(1000)
            .WithMessage("Il campo Url non può superare 1000 caratteri.");

        RuleFor(x => x.ThumbnailStorageKey)
            .MaximumLength(500)
            .WithMessage("Il campo ThumbnailStorageKey non può superare 500 caratteri.");

        RuleFor(x => x.FileSizeBytes)
            .InclusiveBetween((long)0, (long)long.MaxValue)
            .WithMessage("Il campo FileSizeBytes deve essere compreso tra 0 e long.MaxValue.");

        RuleFor(x => x.Title)
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
