using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for CreateTeamMemberDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateTeamMemberDtoValidator : AbstractValidator<Prym.DTOs.Teams.CreateTeamMemberDto>
{
    public CreateTeamMemberDtoValidator()
    {
        RuleFor(x => x.FirstName)
            .NotEmpty()
            .WithMessage("Il campo FirstName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo FirstName non può superare 100 caratteri.");

        RuleFor(x => x.LastName)
            .NotEmpty()
            .WithMessage("Il campo LastName è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo LastName non può superare 100 caratteri.");

        RuleFor(x => x.Email)
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.")
            .MaximumLength(100)
            .WithMessage("Il campo Email non può superare 100 caratteri.");

        RuleFor(x => x.Role)
            .MaximumLength(50)
            .WithMessage("Il campo Role non può superare 50 caratteri.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.FiscalCode)
            .MaximumLength(16)
            .WithMessage("Il campo FiscalCode non può superare 16 caratteri.");

        RuleFor(x => x.Position)
            .MaximumLength(50)
            .WithMessage("Il campo Position non può superare 50 caratteri.");

        RuleFor(x => x.JerseyNumber)
            .InclusiveBetween((int)1, (int)999)
            .WithMessage("Il campo JerseyNumber deve essere compreso tra 1 e 999.");

        RuleFor(x => x.EligibilityStatus)
            .IsInEnum()
            .WithMessage("Il campo EligibilityStatus deve essere un valore valido.");
    }
}
