using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for UpdateTeamDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateTeamDtoValidator : AbstractValidator<Prym.DTOs.Teams.UpdateTeamDto>
{
    public UpdateTeamDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.ShortDescription)
            .MaximumLength(200)
            .WithMessage("Il campo ShortDescription non può superare 200 caratteri.");

        RuleFor(x => x.LongDescription)
            .MaximumLength(1000)
            .WithMessage("Il campo LongDescription non può superare 1000 caratteri.");

        RuleFor(x => x.Email)
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.")
            .MaximumLength(100)
            .WithMessage("Il campo Email non può superare 100 caratteri.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.ClubCode)
            .MaximumLength(50)
            .WithMessage("Il campo ClubCode non può superare 50 caratteri.");

        RuleFor(x => x.FederationCode)
            .MaximumLength(50)
            .WithMessage("Il campo FederationCode non può superare 50 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(50)
            .WithMessage("Il campo Category non può superare 50 caratteri.");
    }
}
