using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for UpdateInsurancePolicyDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateInsurancePolicyDtoValidator : AbstractValidator<Prym.DTOs.Teams.UpdateInsurancePolicyDto>
{
    public UpdateInsurancePolicyDtoValidator()
    {
        RuleFor(x => x.Provider)
            .MaximumLength(100)
            .WithMessage("Il campo Provider non può superare 100 caratteri.");

        RuleFor(x => x.PolicyNumber)
            .MaximumLength(50)
            .WithMessage("Il campo PolicyNumber non può superare 50 caratteri.");

        RuleFor(x => x.CoverageType)
            .MaximumLength(100)
            .WithMessage("Il campo CoverageType non può superare 100 caratteri.");

        RuleFor(x => x.CoverageAmount)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo CoverageAmount deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Currency)
            .MaximumLength(3)
            .WithMessage("Il campo Currency non può superare 3 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
