using FluentValidation;

namespace EventForge.Server.Validators.Teams;

/// <summary>
/// FluentValidation validator for UpdateDocumentReferenceDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentReferenceDtoValidator : AbstractValidator<Prym.DTOs.Teams.UpdateDocumentReferenceDto>
{
    public UpdateDocumentReferenceDtoValidator()
    {
        RuleFor(x => x.FileName)
            .MaximumLength(255)
            .WithMessage("Il campo FileName non può superare 255 caratteri.");

        RuleFor(x => x.Url)
            .MaximumLength(1000)
            .WithMessage("Il campo Url non può superare 1000 caratteri.");

        RuleFor(x => x.ThumbnailStorageKey)
            .MaximumLength(500)
            .WithMessage("Il campo ThumbnailStorageKey non può superare 500 caratteri.");

        RuleFor(x => x.Title)
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
