using FluentValidation;

namespace EventForge.Server.Validators.UnitOfMeasures;

/// <summary>
/// FluentValidation validator for CreateUMDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateUMDtoValidator : AbstractValidator<Prym.DTOs.UnitOfMeasures.CreateUMDto>
{
    public CreateUMDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Symbol)
            .NotEmpty()
            .WithMessage("Il campo Symbol è obbligatorio.")
            .MaximumLength(10)
            .WithMessage("Il campo Symbol non può superare 10 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");
    }
}
