using FluentValidation;

namespace EventForge.Server.Validators.UnitOfMeasures;

/// <summary>
/// FluentValidation validator for UpdateUMDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateUMDtoValidator : AbstractValidator<Prym.DTOs.UnitOfMeasures.UpdateUMDto>
{
    public UpdateUMDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");
    }
}
