using FluentValidation;

namespace EventForge.Server.Validators.Banks;

/// <summary>
/// FluentValidation validator for UpdateBankDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateBankDtoValidator : AbstractValidator<Prym.DTOs.Banks.UpdateBankDto>
{
    public UpdateBankDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Branch)
            .MaximumLength(100)
            .WithMessage("Il campo Branch non può superare 100 caratteri.");

        RuleFor(x => x.Address)
            .MaximumLength(200)
            .WithMessage("Il campo Address non può superare 200 caratteri.");

        RuleFor(x => x.Country)
            .MaximumLength(50)
            .WithMessage("Il campo Country non può superare 50 caratteri.");

        RuleFor(x => x.Phone)
            .MaximumLength(30)
            .WithMessage("Il campo Phone non può superare 30 caratteri.");

        RuleFor(x => x.Email)
            .MaximumLength(100)
            .WithMessage("Il campo Email non può superare 100 caratteri.")
            .EmailAddress()
            .WithMessage("Il campo Email deve contenere un indirizzo email valido.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");
    }
}
