using FluentValidation;

namespace EventForge.Server.Validators.PaymentTerminal;

/// <summary>
/// FluentValidation validator for PaymentRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class PaymentRequestDtoValidator : AbstractValidator<Prym.DTOs.PaymentTerminal.PaymentRequestDto>
{
    public PaymentRequestDtoValidator()
    {
        RuleFor(x => x.Amount)
            .InclusiveBetween((decimal)0.01, (decimal)999999.99)
            .WithMessage("Il campo Amount deve essere compreso tra 0.01 e 999999.99.");

        RuleFor(x => x.ReferenceId)
            .MaximumLength(50)
            .WithMessage("Il campo ReferenceId non può superare 50 caratteri.");
    }
}
