using FluentValidation;

namespace EventForge.Server.Validators.PaymentTerminal;

/// <summary>
/// FluentValidation validator for UpdatePaymentTerminalDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdatePaymentTerminalDtoValidator : AbstractValidator<Prym.DTOs.PaymentTerminal.UpdatePaymentTerminalDto>
{
    public UpdatePaymentTerminalDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");

        RuleFor(x => x.ConnectionType)
            .NotEmpty()
            .WithMessage("Il campo ConnectionType è obbligatorio.")
            .Matches("^(Tcp|TcpViaAgent)$")
            .WithMessage("Il campo ConnectionType non è nel formato corretto.")
            .MaximumLength(20)
            .WithMessage("Il campo ConnectionType non può superare 20 caratteri.");

        RuleFor(x => x.IpAddress)
            .MaximumLength(45)
            .WithMessage("Il campo IpAddress non può superare 45 caratteri.");

        RuleFor(x => x.Port)
            .InclusiveBetween((int)1, (int)65535)
            .WithMessage("Il campo Port deve essere compreso tra 1 e 65535.");

        RuleFor(x => x.TimeoutMs)
            .InclusiveBetween((int)1000, (int)120000)
            .WithMessage("Il campo TimeoutMs deve essere compreso tra 1000 e 120000.");

        RuleFor(x => x.TerminalId)
            .MaximumLength(8)
            .WithMessage("Il campo TerminalId non può superare 8 caratteri.");
    }
}
