using FluentValidation;

namespace EventForge.Server.Validators.Logging;

/// <summary>
/// FluentValidation validator for AgentLogBatchDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AgentLogBatchDtoValidator : AbstractValidator<Prym.DTOs.Logging.AgentLogBatchDto>
{
    public AgentLogBatchDtoValidator()
    {
        RuleFor(x => x.InstallationName)
            .NotEmpty()
            .WithMessage("Il campo InstallationName è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo InstallationName non può superare 200 caratteri.");

        RuleFor(x => x.Logs)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo Logs deve contenere almeno 1 elemento/i.");
    }
}
