using FluentValidation;

namespace EventForge.Server.Validators.Settings;

/// <summary>
/// FluentValidation validator for SaveConfigurationRequest.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SaveConfigurationRequestValidator : AbstractValidator<Prym.DTOs.Settings.SaveConfigurationRequest>
{
    public SaveConfigurationRequestValidator()
    {
        RuleFor(x => x.ServerAddress)
            .NotEmpty()
            .WithMessage("Il campo ServerAddress è obbligatorio.");

        RuleFor(x => x.DatabaseName)
            .NotEmpty()
            .WithMessage("Il campo DatabaseName è obbligatorio.");

        RuleFor(x => x.AuthenticationType)
            .NotEmpty()
            .WithMessage("Il campo AuthenticationType è obbligatorio.");
    }
}
