using FluentValidation;

namespace EventForge.Server.Validators.FiscalPrinting;

/// <summary>
/// FluentValidation validator for FiscalPrinterSetupDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class FiscalPrinterSetupDtoValidator : AbstractValidator<Prym.DTOs.FiscalPrinting.FiscalPrinterSetupDto>
{
    public FiscalPrinterSetupDtoValidator()
    {
        RuleFor(x => x.ConnectionType)
            .NotEmpty()
            .WithMessage("Il campo ConnectionType è obbligatorio.")
            .MaximumLength(20)
            .WithMessage("Il campo ConnectionType non può superare 20 caratteri.");

        RuleFor(x => x.IpAddress)
            .MaximumLength(50)
            .WithMessage("Il campo IpAddress non può superare 50 caratteri.");

        RuleFor(x => x.TcpPort)
            .InclusiveBetween((int)1, (int)65535)
            .WithMessage("Il campo TcpPort deve essere compreso tra 1 e 65535.");

        RuleFor(x => x.SerialPortName)
            .MaximumLength(20)
            .WithMessage("Il campo SerialPortName non può superare 20 caratteri.");

        RuleFor(x => x.BaudRate)
            .InclusiveBetween((int)300, (int)115200)
            .WithMessage("Il campo BaudRate deve essere compreso tra 300 e 115200.");

        RuleFor(x => x.UsbDeviceId)
            .MaximumLength(100)
            .WithMessage("Il campo UsbDeviceId non può superare 100 caratteri.");

        RuleFor(x => x.PrinterWidth)
            .InclusiveBetween((int)10, (int)200)
            .WithMessage("Il campo PrinterWidth deve essere compreso tra 10 e 200.");

        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Location)
            .MaximumLength(50)
            .WithMessage("Il campo Location non può superare 50 caratteri.");

        RuleFor(x => x.ProtocolType)
            .MaximumLength(50)
            .WithMessage("Il campo ProtocolType non può superare 50 caratteri.");
    }
}
