using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for BarcodeRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BarcodeRequestDtoValidator : AbstractValidator<Prym.DTOs.Common.BarcodeRequestDto>
{
    public BarcodeRequestDtoValidator()
    {
        RuleFor(x => x.Data)
            .NotEmpty()
            .WithMessage("Il campo Data è obbligatorio.")
            .MinimumLength(1)
            .WithMessage("Il campo Data deve contenere almeno 1 caratteri.")
            .MaximumLength(1000)
            .WithMessage("Il campo Data non può superare 1000 caratteri.");
    }
}
