using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for ClientLogDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ClientLogDtoValidator : AbstractValidator<Prym.DTOs.Common.ClientLogDto>
{
    public ClientLogDtoValidator()
    {
        RuleFor(x => x.Level)
            .NotEmpty()
            .WithMessage("Il campo Level è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo Level non può superare 50 caratteri.");

        RuleFor(x => x.Message)
            .NotEmpty()
            .WithMessage("Il campo Message è obbligatorio.")
            .MaximumLength(5000)
            .WithMessage("Il campo Message non può superare 5000 caratteri.");

        RuleFor(x => x.Page)
            .MaximumLength(500)
            .WithMessage("Il campo Page non può superare 500 caratteri.");

        RuleFor(x => x.UserName)
            .MaximumLength(100)
            .WithMessage("Il campo UserName non può superare 100 caratteri.");

        RuleFor(x => x.Exception)
            .MaximumLength(10000)
            .WithMessage("Il campo Exception non può superare 10000 caratteri.");

        RuleFor(x => x.UserAgent)
            .MaximumLength(500)
            .WithMessage("Il campo UserAgent non può superare 500 caratteri.");

        RuleFor(x => x.Properties)
            .MaximumLength(5000)
            .WithMessage("Il campo Properties non può superare 5000 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(200)
            .WithMessage("Il campo Category non può superare 200 caratteri.");
    }
}
