using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for CreateContactDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateContactDtoValidator : AbstractValidator<Prym.DTOs.Common.CreateContactDto>
{
    public CreateContactDtoValidator()
    {
        RuleFor(x => x.OwnerType)
            .NotEmpty()
            .WithMessage("Il campo OwnerType è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo OwnerType non può superare 50 caratteri.");

        RuleFor(x => x.Value)
            .NotEmpty()
            .WithMessage("Il campo Value è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Value non può superare 100 caratteri.");

        RuleFor(x => x.Relationship)
            .MaximumLength(50)
            .WithMessage("Il campo Relationship non può superare 50 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(100)
            .WithMessage("Il campo Notes non può superare 100 caratteri.");
    }
}
