using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for CreateReferenceDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateReferenceDtoValidator : AbstractValidator<Prym.DTOs.Common.CreateReferenceDto>
{
    public CreateReferenceDtoValidator()
    {
        RuleFor(x => x.OwnerType)
            .NotEmpty()
            .WithMessage("Il campo OwnerType è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo OwnerType non può superare 50 caratteri.");

        RuleFor(x => x.FirstName)
            .NotEmpty()
            .WithMessage("Il campo FirstName è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo FirstName non può superare 50 caratteri.");

        RuleFor(x => x.LastName)
            .NotEmpty()
            .WithMessage("Il campo LastName è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo LastName non può superare 50 caratteri.");

        RuleFor(x => x.Department)
            .MaximumLength(50)
            .WithMessage("Il campo Department non può superare 50 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(100)
            .WithMessage("Il campo Notes non può superare 100 caratteri.");
    }
}
