using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for CreateAddressDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateAddressDtoValidator : AbstractValidator<Prym.DTOs.Common.CreateAddressDto>
{
    public CreateAddressDtoValidator()
    {
        RuleFor(x => x.OwnerType)
            .NotEmpty()
            .WithMessage("Il campo OwnerType è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo OwnerType non può superare 50 caratteri.");

        RuleFor(x => x.Street)
            .MaximumLength(100)
            .WithMessage("Il campo Street non può superare 100 caratteri.");

        RuleFor(x => x.City)
            .MaximumLength(50)
            .WithMessage("Il campo City non può superare 50 caratteri.");

        RuleFor(x => x.ZipCode)
            .MaximumLength(10)
            .WithMessage("Il campo ZipCode non può superare 10 caratteri.");

        RuleFor(x => x.Province)
            .MaximumLength(50)
            .WithMessage("Il campo Province non può superare 50 caratteri.");

        RuleFor(x => x.Country)
            .MaximumLength(50)
            .WithMessage("Il campo Country non può superare 50 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(100)
            .WithMessage("Il campo Notes non può superare 100 caratteri.");
    }
}
