using FluentValidation;

namespace EventForge.Server.Validators.Common;

/// <summary>
/// FluentValidation validator for UpdateClassificationNodeDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateClassificationNodeDtoValidator : AbstractValidator<Prym.DTOs.Common.UpdateClassificationNodeDto>
{
    public UpdateClassificationNodeDtoValidator()
    {
        RuleFor(x => x.Code)
            .MaximumLength(30)
            .WithMessage("Il campo Code non può superare 30 caratteri.");

        RuleFor(x => x.Name)
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");

        RuleFor(x => x.Type)
            .IsInEnum()
            .WithMessage("Il campo Type deve essere un valore valido.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.Level)
            .InclusiveBetween((int)0, (int)10)
            .WithMessage("Il campo Level deve essere compreso tra 0 e 10.");

        RuleFor(x => x.Order)
            .InclusiveBetween((int)0, (int)1000)
            .WithMessage("Il campo Order deve essere compreso tra 0 e 1000.");
    }
}
