using FluentValidation;

namespace EventForge.Server.Validators.Bulk;

/// <summary>
/// FluentValidation validator for BulkStatusChangeDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BulkStatusChangeDtoValidator : AbstractValidator<Prym.DTOs.Bulk.BulkStatusChangeDto>
{
    public BulkStatusChangeDtoValidator()
    {
        RuleFor(x => x.DocumentIds)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo DocumentIds deve contenere almeno 1 elemento/i.")
            .Must(v => v == null || v.Count <= 500)
            .WithMessage("Il campo DocumentIds non può contenere più di 500 elemento/i.");

        RuleFor(x => x.NewStatus)
            .NotEmpty()
            .WithMessage("Il campo NewStatus è obbligatorio.")
            .MaximumLength(50)
            .WithMessage("Il campo NewStatus non può superare 50 caratteri.");

        RuleFor(x => x.Reason)
            .MaximumLength(1000)
            .WithMessage("Il campo Reason non può superare 1000 caratteri.");
    }
}
