using FluentValidation;

namespace EventForge.Server.Validators.Bulk;

/// <summary>
/// FluentValidation validator for BulkTransferDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BulkTransferDtoValidator : AbstractValidator<Prym.DTOs.Bulk.BulkTransferDto>
{
    public BulkTransferDtoValidator()
    {
        RuleFor(x => x.Items)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo Items deve contenere almeno 1 elemento/i.")
            .Must(v => v == null || v.Count <= 500)
            .WithMessage("Il campo Items non può contenere più di 500 elemento/i.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
