using FluentValidation;

namespace EventForge.Server.Validators.Bulk;

/// <summary>
/// FluentValidation validator for BulkUpdatePricesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BulkUpdatePricesDtoValidator : AbstractValidator<Prym.DTOs.Bulk.BulkUpdatePricesDto>
{
    public BulkUpdatePricesDtoValidator()
    {
        RuleFor(x => x.ProductIds)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo ProductIds deve contenere almeno 1 elemento/i.")
            .Must(v => v == null || v.Count <= 500)
            .WithMessage("Il campo ProductIds non può contenere più di 500 elemento/i.");

        RuleFor(x => x.UpdateType)
            .IsInEnum()
            .WithMessage("Il campo UpdateType deve essere un valore valido.");

        RuleFor(x => x.NewPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo NewPrice deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Percentage)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo Percentage deve essere compreso tra 0 e 100.");

        RuleFor(x => x.Amount)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Amount deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
