using FluentValidation;

namespace EventForge.Server.Validators.Business;

/// <summary>
/// FluentValidation validator for CreateBusinessPartyGroupDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateBusinessPartyGroupDtoValidator : AbstractValidator<Prym.DTOs.Business.CreateBusinessPartyGroupDto>
{
    public CreateBusinessPartyGroupDtoValidator()
    {
        RuleFor(x => x.ColorHex)
            .MinimumLength(7)
            .WithMessage("Il campo ColorHex deve contenere almeno 7 caratteri.")
            .MaximumLength(7)
            .WithMessage("Il campo ColorHex non può superare 7 caratteri.")
            .Matches(@"^#[0-9A-Fa-f]{6}$")
            .WithMessage("Il campo ColorHex non è nel formato corretto.");
    }
}
