using FluentValidation;

namespace EventForge.Server.Validators.Business;

/// <summary>
/// FluentValidation validator for UpdatePaymentTermDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdatePaymentTermDtoValidator : AbstractValidator<Prym.DTOs.Business.UpdatePaymentTermDto>
{
    public UpdatePaymentTermDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(250)
            .WithMessage("Il campo Description non può superare 250 caratteri.");

        RuleFor(x => x.DueDays)
            .InclusiveBetween((int)0, (int)365)
            .WithMessage("Il campo DueDays deve essere compreso tra 0 e 365.");
    }
}
