using FluentValidation;

namespace EventForge.Server.Validators.Chat;

/// <summary>
/// FluentValidation validator for ChatExportRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ChatExportRequestDtoValidator : AbstractValidator<Prym.DTOs.Chat.ChatExportRequestDto>
{
    public ChatExportRequestDtoValidator()
    {
        RuleFor(x => x.Format)
            .NotEmpty()
            .WithMessage("Il campo Format è obbligatorio.");

        RuleFor(x => x.MaxRecords)
            .InclusiveBetween((int)1, (int)100000)
            .WithMessage("Il campo MaxRecords deve essere compreso tra 1 e 100000.");
    }
}
