using FluentValidation;

namespace EventForge.Server.Validators.Chat;

/// <summary>
/// FluentValidation validator for CreateChatDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateChatDtoValidator : AbstractValidator<Prym.DTOs.Chat.CreateChatDto>
{
    public CreateChatDtoValidator()
    {
        RuleFor(x => x.Type)
            .IsInEnum()
            .WithMessage("Il campo Type deve essere un valore valido.");

        RuleFor(x => x.Name)
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.PreferredLocale)
            .MaximumLength(10)
            .WithMessage("Il campo PreferredLocale non può superare 10 caratteri.");
    }
}
