using FluentValidation;

namespace EventForge.Server.Validators.Chat;

/// <summary>
/// FluentValidation validator for EditMessageRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class EditMessageRequestDtoValidator : AbstractValidator<Prym.DTOs.Chat.EditMessageRequestDto>
{
    public EditMessageRequestDtoValidator()
    {
        RuleFor(x => x.Content)
            .NotEmpty()
            .WithMessage("Il campo Content è obbligatorio.")
            .MaximumLength(4000)
            .WithMessage("Il campo Content non può superare 4000 caratteri.");
    }
}
