using FluentValidation;

namespace EventForge.Server.Validators.Chat;

/// <summary>
/// FluentValidation validator for ReportMessageDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ReportMessageDtoValidator : AbstractValidator<Prym.DTOs.Chat.ReportMessageDto>
{
    public ReportMessageDtoValidator()
    {
        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
