using FluentValidation;

namespace EventForge.Server.Validators.Chat;

/// <summary>
/// FluentValidation validator for SendMessageDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SendMessageDtoValidator : AbstractValidator<Prym.DTOs.Chat.SendMessageDto>
{
    public SendMessageDtoValidator()
    {
        RuleFor(x => x.Content)
            .MaximumLength(4000)
            .WithMessage("Il campo Content non può superare 4000 caratteri.");

        RuleFor(x => x.Locale)
            .MaximumLength(10)
            .WithMessage("Il campo Locale non può superare 10 caratteri.");
    }
}
