using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for AddSessionNoteDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AddSessionNoteDtoValidator : AbstractValidator<Prym.DTOs.Sales.AddSessionNoteDto>
{
    public AddSessionNoteDtoValidator()
    {
        RuleFor(x => x.Text)
            .NotEmpty()
            .WithMessage("Il campo Text è obbligatorio.")
            .MaximumLength(1000)
            .WithMessage("Il campo Text non può superare 1000 caratteri.");
    }
}
