using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for AddSalePaymentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AddSalePaymentDtoValidator : AbstractValidator<Prym.DTOs.Sales.AddSalePaymentDto>
{
    public AddSalePaymentDtoValidator()
    {
        RuleFor(x => x.Amount)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Amount deve essere compreso tra 0.01 e decimal.MaxValue.");

        RuleFor(x => x.TransactionReference)
            .MaximumLength(200)
            .WithMessage("Il campo TransactionReference non può superare 200 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
