using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for AddSaleItemDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AddSaleItemDtoValidator : AbstractValidator<Prym.DTOs.Sales.AddSaleItemDto>
{
    public AddSaleItemDtoValidator()
    {
        RuleFor(x => x.Quantity)
            .InclusiveBetween((decimal)0.001, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Quantity deve essere compreso tra 0.001 e decimal.MaxValue.");

        RuleFor(x => x.DiscountPercent)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscountPercent deve essere compreso tra 0 e 100.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
