using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for ApplyGlobalDiscountDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ApplyGlobalDiscountDtoValidator : AbstractValidator<Prym.DTOs.Sales.ApplyGlobalDiscountDto>
{
    public ApplyGlobalDiscountDtoValidator()
    {
        RuleFor(x => x.DiscountPercent)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo DiscountPercent deve essere compreso tra 0 e 100.");

        RuleFor(x => x.Reason)
            .MaximumLength(500)
            .WithMessage("Il campo Reason non può superare 500 caratteri.");
    }
}
