using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for CreateTableReservationDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateTableReservationDtoValidator : AbstractValidator<Prym.DTOs.Sales.CreateTableReservationDto>
{
    public CreateTableReservationDtoValidator()
    {
        RuleFor(x => x.CustomerName)
            .NotEmpty()
            .WithMessage("Il campo CustomerName è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo CustomerName non può superare 200 caratteri.");

        RuleFor(x => x.PhoneNumber)
            .MaximumLength(20)
            .WithMessage("Il campo PhoneNumber non può superare 20 caratteri.");

        RuleFor(x => x.NumberOfGuests)
            .InclusiveBetween((int)1, (int)50)
            .WithMessage("Il campo NumberOfGuests deve essere compreso tra 1 e 50.");

        RuleFor(x => x.DurationMinutes)
            .InclusiveBetween((int)15, (int)480)
            .WithMessage("Il campo DurationMinutes deve essere compreso tra 15 e 480.");

        RuleFor(x => x.SpecialRequests)
            .MaximumLength(1000)
            .WithMessage("Il campo SpecialRequests non può superare 1000 caratteri.");
    }
}
