using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for MergeSessionsDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class MergeSessionsDtoValidator : AbstractValidator<Prym.DTOs.Sales.MergeSessionsDto>
{
    public MergeSessionsDtoValidator()
    {
        RuleFor(x => x.SessionIds)
            .Must(v => v != null && v.Count >= 2)
            .WithMessage("Il campo SessionIds deve contenere almeno 2 elemento/i.");

        RuleFor(x => x.MergeReason)
            .MaximumLength(500)
            .WithMessage("Il campo MergeReason non può superare 500 caratteri.");
    }
}
