using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for ReservationCheckInRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ReservationCheckInRequestDtoValidator : AbstractValidator<Prym.DTOs.Sales.ReservationCheckInRequestDto>
{
    public ReservationCheckInRequestDtoValidator()
    {
        RuleFor(x => x.SaleType)
            .MaximumLength(50)
            .WithMessage("Il campo SaleType non può superare 50 caratteri.");

        RuleFor(x => x.Currency)
            .MaximumLength(3)
            .WithMessage("Il campo Currency non può superare 3 caratteri.");
    }
}
