using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for SplitSessionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class SplitSessionDtoValidator : AbstractValidator<Prym.DTOs.Sales.SplitSessionDto>
{
    public SplitSessionDtoValidator()
    {
        RuleFor(x => x.NumberOfPeople)
            .InclusiveBetween((int)2, (int)20)
            .WithMessage("Il campo NumberOfPeople deve essere compreso tra 2 e 20.");

        RuleFor(x => x.SplitType)
            .IsInEnum()
            .WithMessage("Il campo SplitType deve essere un valore valido.");
    }
}
