using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for UpdateNoteFlagDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateNoteFlagDtoValidator : AbstractValidator<Prym.DTOs.Sales.UpdateNoteFlagDto>
{
    public UpdateNoteFlagDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Color)
            .MaximumLength(7)
            .WithMessage("Il campo Color non può superare 7 caratteri.");

        RuleFor(x => x.Icon)
            .MaximumLength(50)
            .WithMessage("Il campo Icon non può superare 50 caratteri.");
    }
}
