using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for UpdateTableStatusDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateTableStatusDtoValidator : AbstractValidator<Prym.DTOs.Sales.UpdateTableStatusDto>
{
    public UpdateTableStatusDtoValidator()
    {
        RuleFor(x => x.Status)
            .NotEmpty()
            .WithMessage("Il campo Status è obbligatorio.");
    }
}
