using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for UpdateTableSessionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateTableSessionDtoValidator : AbstractValidator<Prym.DTOs.Sales.UpdateTableSessionDto>
{
    public UpdateTableSessionDtoValidator()
    {
        RuleFor(x => x.TableNumber)
            .MaximumLength(50)
            .WithMessage("Il campo TableNumber non può superare 50 caratteri.");

        RuleFor(x => x.TableName)
            .MaximumLength(100)
            .WithMessage("Il campo TableName non può superare 100 caratteri.");

        RuleFor(x => x.Capacity)
            .InclusiveBetween((int)1, (int)50)
            .WithMessage("Il campo Capacity deve essere compreso tra 1 e 50.");

        RuleFor(x => x.Width)
            .InclusiveBetween((int)40, (int)300)
            .WithMessage("Il campo Width deve essere compreso tra 40 e 300.");

        RuleFor(x => x.Height)
            .InclusiveBetween((int)40, (int)300)
            .WithMessage("Il campo Height deve essere compreso tra 40 e 300.");

        RuleFor(x => x.Area)
            .MaximumLength(100)
            .WithMessage("Il campo Area non può superare 100 caratteri.");
    }
}
