using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for UpdateSaleSessionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateSaleSessionDtoValidator : AbstractValidator<Prym.DTOs.Sales.UpdateSaleSessionDto>
{
    public UpdateSaleSessionDtoValidator()
    {
        RuleFor(x => x.SaleType)
            .MaximumLength(50)
            .WithMessage("Il campo SaleType non può superare 50 caratteri.");
    }
}
