using FluentValidation;

namespace EventForge.Server.Validators.Sales;

/// <summary>
/// FluentValidation validator for UpdatePaymentMethodDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdatePaymentMethodDtoValidator : AbstractValidator<Prym.DTOs.Sales.UpdatePaymentMethodDto>
{
    public UpdatePaymentMethodDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Icon)
            .MaximumLength(50)
            .WithMessage("Il campo Icon non può superare 50 caratteri.");

        RuleFor(x => x.IntegrationConfig)
            .MaximumLength(2000)
            .WithMessage("Il campo IntegrationConfig non può superare 2000 caratteri.");

        RuleFor(x => x.FiscalCode)
            .InclusiveBetween((int)1, (int)10)
            .WithMessage("Il campo FiscalCode deve essere compreso tra 1 e 10.");
    }
}
