using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for AttachmentVersionDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AttachmentVersionDtoValidator : AbstractValidator<Prym.DTOs.Documents.AttachmentVersionDto>
{
    public AttachmentVersionDtoValidator()
    {
        RuleFor(x => x.FileName)
            .NotEmpty()
            .WithMessage("Il campo FileName è obbligatorio.")
            .MaximumLength(255)
            .WithMessage("Il campo FileName non può superare 255 caratteri.");

        RuleFor(x => x.StoragePath)
            .NotEmpty()
            .WithMessage("Il campo StoragePath è obbligatorio.")
            .MaximumLength(500)
            .WithMessage("Il campo StoragePath non può superare 500 caratteri.");

        RuleFor(x => x.MimeType)
            .NotEmpty()
            .WithMessage("Il campo MimeType è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo MimeType non può superare 100 caratteri.");

        RuleFor(x => x.FileSizeBytes)
            .InclusiveBetween((long)0, (long)long.MaxValue)
            .WithMessage("Il campo FileSizeBytes deve essere compreso tra 0 e long.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
