using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentHeaderDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentHeaderDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentHeaderDto>
{
    public CreateDocumentHeaderDtoValidator()
    {
        RuleFor(x => x.Series)
            .MaximumLength(10)
            .WithMessage("Il campo Series non può superare 10 caratteri.");

        RuleFor(x => x.Number)
            .MaximumLength(30)
            .WithMessage("Il campo Number non può superare 30 caratteri.");

        RuleFor(x => x.CustomerName)
            .MaximumLength(100)
            .WithMessage("Il campo CustomerName non può superare 100 caratteri.");

        RuleFor(x => x.CarrierName)
            .MaximumLength(100)
            .WithMessage("Il campo CarrierName non può superare 100 caratteri.");

        RuleFor(x => x.TrackingNumber)
            .MaximumLength(50)
            .WithMessage("Il campo TrackingNumber non può superare 50 caratteri.");

        RuleFor(x => x.ShippingNotes)
            .MaximumLength(200)
            .WithMessage("Il campo ShippingNotes non può superare 200 caratteri.");

        RuleFor(x => x.ExternalDocumentNumber)
            .MaximumLength(30)
            .WithMessage("Il campo ExternalDocumentNumber non può superare 30 caratteri.");

        RuleFor(x => x.ExternalDocumentSeries)
            .MaximumLength(10)
            .WithMessage("Il campo ExternalDocumentSeries non può superare 10 caratteri.");

        RuleFor(x => x.DocumentReason)
            .MaximumLength(100)
            .WithMessage("Il campo DocumentReason non può superare 100 caratteri.");

        RuleFor(x => x.FiscalDocumentNumber)
            .MaximumLength(30)
            .WithMessage("Il campo FiscalDocumentNumber non può superare 30 caratteri.");

        RuleFor(x => x.Currency)
            .MaximumLength(3)
            .WithMessage("Il campo Currency non può superare 3 caratteri.");

        RuleFor(x => x.PaymentMethod)
            .MaximumLength(30)
            .WithMessage("Il campo PaymentMethod non può superare 30 caratteri.");

        RuleFor(x => x.PaymentReference)
            .MaximumLength(50)
            .WithMessage("Il campo PaymentReference non può superare 50 caratteri.");

        RuleFor(x => x.TotalDiscount)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo TotalDiscount deve essere compreso tra 0 e 100.");

        RuleFor(x => x.TotalDiscountAmount)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo TotalDiscountAmount deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
