using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentAttachmentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentAttachmentDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentAttachmentDto>
{
    public CreateDocumentAttachmentDtoValidator()
    {
        RuleFor(x => x.FileName)
            .NotEmpty()
            .WithMessage("Il campo FileName è obbligatorio.")
            .MaximumLength(255)
            .WithMessage("Il campo FileName non può superare 255 caratteri.");

        RuleFor(x => x.StoragePath)
            .NotEmpty()
            .WithMessage("Il campo StoragePath è obbligatorio.")
            .MaximumLength(500)
            .WithMessage("Il campo StoragePath non può superare 500 caratteri.");

        RuleFor(x => x.MimeType)
            .NotEmpty()
            .WithMessage("Il campo MimeType è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo MimeType non può superare 100 caratteri.");

        RuleFor(x => x.FileSizeBytes)
            .InclusiveBetween((long)0, (long)long.MaxValue)
            .WithMessage("Il campo FileSizeBytes deve essere compreso tra 0 e long.MaxValue.");

        RuleFor(x => x.Title)
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");

        RuleFor(x => x.StorageProvider)
            .MaximumLength(50)
            .WithMessage("Il campo StorageProvider non può superare 50 caratteri.");

        RuleFor(x => x.ExternalReference)
            .MaximumLength(200)
            .WithMessage("Il campo ExternalReference non può superare 200 caratteri.");
    }
}
