using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentCommentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentCommentDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentCommentDto>
{
    public CreateDocumentCommentDtoValidator()
    {
        RuleFor(x => x.Content)
            .NotEmpty()
            .WithMessage("Il campo Content è obbligatorio.")
            .MaximumLength(2000)
            .WithMessage("Il campo Content non può superare 2000 caratteri.");

        RuleFor(x => x.AssignedTo)
            .MaximumLength(100)
            .WithMessage("Il campo AssignedTo non può superare 100 caratteri.");

        RuleFor(x => x.MentionedUsers)
            .MaximumLength(500)
            .WithMessage("Il campo MentionedUsers non può superare 500 caratteri.");

        RuleFor(x => x.Tags)
            .MaximumLength(200)
            .WithMessage("Il campo Tags non può superare 200 caratteri.");

        RuleFor(x => x.Metadata)
            .MaximumLength(1000)
            .WithMessage("Il campo Metadata non può superare 1000 caratteri.");
    }
}
