using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentRecurrenceDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentRecurrenceDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentRecurrenceDto>
{
    public CreateDocumentRecurrenceDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Pattern)
            .IsInEnum()
            .WithMessage("Il campo Pattern deve essere un valore valido.");

        RuleFor(x => x.Interval)
            .InclusiveBetween((int)1, (int)365)
            .WithMessage("Il campo Interval deve essere compreso tra 1 e 365.");

        RuleFor(x => x.DaysOfWeek)
            .MaximumLength(50)
            .WithMessage("Il campo DaysOfWeek non può superare 50 caratteri.");

        RuleFor(x => x.DayOfMonth)
            .InclusiveBetween((int)1, (int)31)
            .WithMessage("Il campo DayOfMonth deve essere compreso tra 1 e 31.");

        RuleFor(x => x.MaxOccurrences)
            .InclusiveBetween((int)1, (int)1000)
            .WithMessage("Il campo MaxOccurrences deve essere compreso tra 1 e 1000.");

        RuleFor(x => x.LeadTimeDays)
            .InclusiveBetween((int)0, (int)365)
            .WithMessage("Il campo LeadTimeDays deve essere compreso tra 0 e 365.");

        RuleFor(x => x.NotificationSettings)
            .MaximumLength(1000)
            .WithMessage("Il campo NotificationSettings non può superare 1000 caratteri.");

        RuleFor(x => x.AdditionalConfig)
            .MaximumLength(2000)
            .WithMessage("Il campo AdditionalConfig non può superare 2000 caratteri.");
    }
}
