using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentWorkflowDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentWorkflowDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentWorkflowDto>
{
    public CreateDocumentWorkflowDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(50)
            .WithMessage("Il campo Category non può superare 50 caratteri.");

        RuleFor(x => x.AutoApprovalThreshold)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo AutoApprovalThreshold deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.EscalationTimeoutHours)
            .InclusiveBetween((int)1, (int)8760)
            .WithMessage("Il campo EscalationTimeoutHours deve essere compreso tra 1 e 8760.");

        RuleFor(x => x.DefaultAssignee)
            .MaximumLength(100)
            .WithMessage("Il campo DefaultAssignee non può superare 100 caratteri.");

        RuleFor(x => x.NotificationConfig)
            .MaximumLength(2000)
            .WithMessage("Il campo NotificationConfig non può superare 2000 caratteri.");
    }
}
