using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for CreateDocumentCounterDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreateDocumentCounterDtoValidator : AbstractValidator<Prym.DTOs.Documents.CreateDocumentCounterDto>
{
    public CreateDocumentCounterDtoValidator()
    {
        RuleFor(x => x.Series)
            .NotEmpty()
            .WithMessage("Il campo Series è obbligatorio.")
            .MaximumLength(10)
            .WithMessage("Il campo Series non può superare 10 caratteri.");

        RuleFor(x => x.Prefix)
            .MaximumLength(10)
            .WithMessage("Il campo Prefix non può superare 10 caratteri.");

        RuleFor(x => x.PaddingLength)
            .InclusiveBetween((int)1, (int)10)
            .WithMessage("Il campo PaddingLength deve essere compreso tra 1 e 10.");

        RuleFor(x => x.FormatPattern)
            .MaximumLength(50)
            .WithMessage("Il campo FormatPattern non può superare 50 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");
    }
}
