using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for DocumentExportRequestDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class DocumentExportRequestDtoValidator : AbstractValidator<Prym.DTOs.Documents.DocumentExportRequestDto>
{
    public DocumentExportRequestDtoValidator()
    {
        RuleFor(x => x.Format)
            .NotEmpty()
            .WithMessage("Il campo Format è obbligatorio.");

        RuleFor(x => x.MaxRecords)
            .InclusiveBetween((int)1, (int)10000)
            .WithMessage("Il campo MaxRecords deve essere compreso tra 1 e 10000.");
    }
}
