using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for ResolveCommentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class ResolveCommentDtoValidator : AbstractValidator<Prym.DTOs.Documents.ResolveCommentDto>
{
    public ResolveCommentDtoValidator()
    {
        RuleFor(x => x.ResolutionNotes)
            .MaximumLength(500)
            .WithMessage("Il campo ResolutionNotes non può superare 500 caratteri.");
    }
}
