using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for UpdateDocumentCommentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentCommentDtoValidator : AbstractValidator<Prym.DTOs.Documents.UpdateDocumentCommentDto>
{
    public UpdateDocumentCommentDtoValidator()
    {
        RuleFor(x => x.Content)
            .MaximumLength(2000)
            .WithMessage("Il campo Content non può superare 2000 caratteri.");

        RuleFor(x => x.AssignedTo)
            .MaximumLength(100)
            .WithMessage("Il campo AssignedTo non può superare 100 caratteri.");

        RuleFor(x => x.Tags)
            .MaximumLength(200)
            .WithMessage("Il campo Tags non può superare 200 caratteri.");

        RuleFor(x => x.Metadata)
            .MaximumLength(1000)
            .WithMessage("Il campo Metadata non può superare 1000 caratteri.");
    }
}
