using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for UpdateDocumentRowDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentRowDtoValidator : AbstractValidator<Prym.DTOs.Documents.UpdateDocumentRowDto>
{
    public UpdateDocumentRowDtoValidator()
    {
        RuleFor(x => x.ProductCode)
            .MaximumLength(50)
            .WithMessage("Il campo ProductCode non può superare 50 caratteri.");

        RuleFor(x => x.Description)
            .NotEmpty()
            .WithMessage("Il campo Description è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Description non può superare 200 caratteri.");

        RuleFor(x => x.UnitOfMeasure)
            .MaximumLength(10)
            .WithMessage("Il campo UnitOfMeasure non può superare 10 caratteri.");

        RuleFor(x => x.UnitPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo UnitPrice deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Quantity)
            .InclusiveBetween((decimal)ValidationConstants.MinimumQuantity, (decimal)ValidationConstants.MaximumQuantity)
            .WithMessage("Il campo Quantity deve essere compreso tra ValidationConstants.MinimumQuantity e ValidationConstants.MaximumQuantity.");

        RuleFor(x => x.LineDiscount)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo LineDiscount deve essere compreso tra 0 e 100.");

        RuleFor(x => x.LineDiscountString)
            .MaximumLength(50)
            .WithMessage("Il campo LineDiscountString non può superare 50 caratteri.");

        RuleFor(x => x.LineDiscountValue)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo LineDiscountValue deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.VatRate)
            .InclusiveBetween((decimal)0, (decimal)100)
            .WithMessage("Il campo VatRate deve essere compreso tra 0 e 100.");

        RuleFor(x => x.VatDescription)
            .MaximumLength(30)
            .WithMessage("Il campo VatDescription non può superare 30 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");

        RuleFor(x => x.PriceNotes)
            .MaximumLength(500)
            .WithMessage("Il campo PriceNotes non può superare 500 caratteri.");

        RuleFor(x => x.AppliedPromotionsJSON)
            .MaximumLength(4000)
            .WithMessage("Il campo AppliedPromotionsJSON non può superare 4000 caratteri.");

        RuleFor(x => x.SupplierGrossPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo SupplierGrossPrice deve essere compreso tra 0 e decimal.MaxValue.");
    }
}
