using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for UpdateDocumentTypeDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentTypeDtoValidator : AbstractValidator<Prym.DTOs.Documents.UpdateDocumentTypeDto>
{
    public UpdateDocumentTypeDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MinimumLength(1)
            .WithMessage("Il campo Name deve contenere almeno 1 caratteri.")
            .MaximumLength(50)
            .WithMessage("Il campo Name non può superare 50 caratteri.");

        RuleFor(x => x.Code)
            .NotEmpty()
            .WithMessage("Il campo Code è obbligatorio.")
            .MinimumLength(1)
            .WithMessage("Il campo Code deve contenere almeno 1 caratteri.")
            .MaximumLength(10)
            .WithMessage("Il campo Code non può superare 10 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(200)
            .WithMessage("Il campo Notes non può superare 200 caratteri.");
    }
}
