using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for UpdateDocumentAttachmentDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentAttachmentDtoValidator : AbstractValidator<Prym.DTOs.Documents.UpdateDocumentAttachmentDto>
{
    public UpdateDocumentAttachmentDtoValidator()
    {
        RuleFor(x => x.Title)
            .MaximumLength(200)
            .WithMessage("Il campo Title non può superare 200 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
