using FluentValidation;

namespace EventForge.Server.Validators.Documents;

/// <summary>
/// FluentValidation validator for UpdateDocumentTemplateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdateDocumentTemplateDtoValidator : AbstractValidator<Prym.DTOs.Documents.UpdateDocumentTemplateDto>
{
    public UpdateDocumentTemplateDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Category)
            .MaximumLength(50)
            .WithMessage("Il campo Category non può superare 50 caratteri.");

        RuleFor(x => x.Owner)
            .MaximumLength(100)
            .WithMessage("Il campo Owner non può superare 100 caratteri.");

        RuleFor(x => x.DefaultPaymentMethod)
            .MaximumLength(30)
            .WithMessage("Il campo DefaultPaymentMethod non può superare 30 caratteri.");

        RuleFor(x => x.DefaultNotes)
            .MaximumLength(500)
            .WithMessage("Il campo DefaultNotes non può superare 500 caratteri.");
    }
}
