using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for AssignBusinessPartyToPriceListDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class AssignBusinessPartyToPriceListDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.AssignBusinessPartyToPriceListDto>
{
    public AssignBusinessPartyToPriceListDtoValidator()
    {
        RuleFor(x => x.OverridePriority)
            .InclusiveBetween((int)0, (int)100)
            .WithMessage("Il campo OverridePriority deve essere compreso tra 0 e 100.");

        RuleFor(x => x.GlobalDiscountPercentage)
            .InclusiveBetween((decimal)-100, (decimal)100)
            .WithMessage("Il campo GlobalDiscountPercentage deve essere compreso tra -100 e 100.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
