using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for BatchPriceResolutionRequest.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BatchPriceResolutionRequestValidator : AbstractValidator<Prym.DTOs.PriceLists.BatchPriceResolutionRequest>
{
    public BatchPriceResolutionRequestValidator()
    {
        RuleFor(x => x.Items)
            .Must(v => v != null && v.Count >= 1)
            .WithMessage("Il campo Items deve contenere almeno 1 elemento/i.")
            .Must(v => v == null || v.Count <= 100)
            .WithMessage("Il campo Items non può contenere più di 100 elemento/i.");
    }
}
