using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for BulkPriceUpdateDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class BulkPriceUpdateDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.BulkPriceUpdateDto>
{
    public BulkPriceUpdateDtoValidator()
    {
        RuleFor(x => x.Value)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Value deve essere compreso tra 0.01 e decimal.MaxValue.");

        RuleFor(x => x.MinPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MinPrice deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.MaxPrice)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MaxPrice deve essere compreso tra 0 e decimal.MaxValue.");
    }
}
