using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for CreatePriceListEntryDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class CreatePriceListEntryDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.CreatePriceListEntryDto>
{
    public CreatePriceListEntryDtoValidator()
    {
        RuleFor(x => x.Price)
            .InclusiveBetween((decimal)0, (decimal)decimal.MaxValue)
            .WithMessage("Il campo Price deve essere compreso tra 0 e decimal.MaxValue.");

        RuleFor(x => x.Currency)
            .MaximumLength(3)
            .WithMessage("Il campo Currency non può superare 3 caratteri.");

        RuleFor(x => x.Score)
            .InclusiveBetween((int)0, (int)100)
            .WithMessage("Il campo Score deve essere compreso tra 0 e 100.");

        RuleFor(x => x.MinQuantity)
            .InclusiveBetween((int)1, (int)int.MaxValue)
            .WithMessage("Il campo MinQuantity deve essere compreso tra 1 e int.MaxValue.");

        RuleFor(x => x.MaxQuantity)
            .InclusiveBetween((int)0, (int)int.MaxValue)
            .WithMessage("Il campo MaxQuantity deve essere compreso tra 0 e int.MaxValue.");

        RuleFor(x => x.Notes)
            .MaximumLength(500)
            .WithMessage("Il campo Notes non può superare 500 caratteri.");
    }
}
