using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for DuplicatePriceListDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class DuplicatePriceListDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.DuplicatePriceListDto>
{
    public DuplicatePriceListDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");
    }
}
