using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for GeneratePriceListFromPurchasesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class GeneratePriceListFromPurchasesDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.GeneratePriceListFromPurchasesDto>
{
    public GeneratePriceListFromPurchasesDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");

        RuleFor(x => x.MarkupPercentage)
            .InclusiveBetween((decimal)-100, (decimal)1000)
            .WithMessage("Il campo MarkupPercentage deve essere compreso tra -100 e 1000.");

        RuleFor(x => x.MinimumQuantity)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MinimumQuantity deve essere compreso tra 0.01 e decimal.MaxValue.");
    }
}
