using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for GeneratePriceListFromProductsDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class GeneratePriceListFromProductsDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.GeneratePriceListFromProductsDto>
{
    public GeneratePriceListFromProductsDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");

        RuleFor(x => x.Priority)
            .InclusiveBetween((int)0, (int)100)
            .WithMessage("Il campo Priority deve essere compreso tra 0 e 100.");

        RuleFor(x => x.MarkupPercentage)
            .InclusiveBetween((decimal)-100, (decimal)1000)
            .WithMessage("Il campo MarkupPercentage deve essere compreso tra -100 e 1000.");
    }
}
