using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for GenerateFromDefaultPricesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class GenerateFromDefaultPricesDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.GenerateFromDefaultPricesDto>
{
    public GenerateFromDefaultPricesDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(200)
            .WithMessage("Il campo Name non può superare 200 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Code)
            .MaximumLength(50)
            .WithMessage("Il campo Code non può superare 50 caratteri.");

        RuleFor(x => x.Priority)
            .InclusiveBetween((int)0, (int)100)
            .WithMessage("Il campo Priority deve essere compreso tra 0 e 100.");

        RuleFor(x => x.MarkupPercentage)
            .InclusiveBetween((decimal)-100, (decimal)500)
            .WithMessage("Il campo MarkupPercentage deve essere compreso tra -100 e 500.");

        RuleFor(x => x.MinimumPrice)
            .InclusiveBetween((decimal)0.01, (decimal)decimal.MaxValue)
            .WithMessage("Il campo MinimumPrice deve essere compreso tra 0.01 e decimal.MaxValue.");
    }
}
