using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for UpdatePriceListFromPurchasesDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdatePriceListFromPurchasesDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.UpdatePriceListFromPurchasesDto>
{
    public UpdatePriceListFromPurchasesDtoValidator()
    {
        RuleFor(x => x.MarkupPercentage)
            .InclusiveBetween((decimal)-100, (decimal)1000)
            .WithMessage("Il campo MarkupPercentage deve essere compreso tra -100 e 1000.");
    }
}
