using FluentValidation;

namespace EventForge.Server.Validators.PriceLists;

/// <summary>
/// FluentValidation validator for UpdatePriceListDto.
/// Auto-generated by scripts/FluentValidationGenerator; TODO-REVIEW comments require manual follow-up.
/// </summary>
public class UpdatePriceListDtoValidator : AbstractValidator<Prym.DTOs.PriceLists.UpdatePriceListDto>
{
    public UpdatePriceListDtoValidator()
    {
        RuleFor(x => x.Name)
            .NotEmpty()
            .WithMessage("Il campo Name è obbligatorio.")
            .MaximumLength(100)
            .WithMessage("Il campo Name non può superare 100 caratteri.");

        RuleFor(x => x.Description)
            .MaximumLength(500)
            .WithMessage("Il campo Description non può superare 500 caratteri.");

        RuleFor(x => x.Notes)
            .MaximumLength(1000)
            .WithMessage("Il campo Notes non può superare 1000 caratteri.");

        RuleFor(x => x.Status)
            .IsInEnum()
            .WithMessage("Il campo Status deve essere un valore valido.");

        RuleFor(x => x.Priority)
            .InclusiveBetween((int)0, (int)100)
            .WithMessage("Il campo Priority deve essere compreso tra 0 e 100.");
    }
}
